### ISSUE TITLE
Validating Select

### ISSUE THREAD

**Issue by elvnthaus** [creativetimofficial/ct-material-kit-pro#10]
I'm having a hard time getting the `<select>` elements integrated into  reactive form. The dynamic classes (ng-valid, ng-touched, etc) aren't working properly.

```
<div [class.has-success]="quoteRequestForm.get('services').touched"
     [class.has-error]="quoteRequestForm.get('services').touched && quoteRequestForm.get('services').hasError('required')"
     class="form-group label-floating form-warning">
     <label for="services" class="control-label">Services</label>
     <select multiple id="services" formControlName="services" class="select form-control">
          <option value="Cat Sitting">Cat Sitting</option>
          <option value="Dog Walking">Dog Walking</option>
          <option value="Dog Daycare">Dog Daycare</option>
          <option value="Dog Boarding">Dog Boarding</option>
          <option value="Overnight Care">Overnight Care</option>
     </select>
</div>
```

But the classes on the select element don't change dynamically based on user input.

<img width="288" alt="screen shot 2017-04-12 at 1 46 21 pm" src="https://cloud.githubusercontent.com/assets/12756576/24978713/81bbb240-1f86-11e7-9f18-f7723197b436.png">

Am I missing something?

**Comment by alexandru-paduraru** [comment]
@elvnthaus we just did the V1.1.0 update which contains a better Select library: http://silviomoreto.github.io/bootstrap-select/ and I think that will help you more than the original select plugin.

Please check it and let us know if that is better. Also if you have any feedback for v1.1.0 we would appreciate if you share it with us.

Best,
Alex

**Comment by elvnthaus** [comment]
Looks like because bootstrap-select is built using jquery and angular 2 reactive forms don't play well with jquery I'm going to go another route.

**Comment by alexandru-paduraru** [comment]
@elvnthaus please let us know the second route, maybe there are other users who are facing the same issue and together we can find a solution.

Best,
Alex
