### ISSUE TITLE
boostrap select live search blocks when an input doesn't have match

### ISSUE THREAD

**Issue by robertofd1995** [creativetimofficial/ct-material-kit-pro#100]
Problem : 

When the live search is active , there is a bug when the user introduce an input that is not on the list.
The box shows that there is not result that match but after that (even if you delete the text) the box keeps active and if you click out doesn't close anymore , even if you later select a valid option

Steps to reproduce it : 

1. Insert this code

``` html
<select class="selectpicker show-tick" name="categoriasInput" data-style="select-with-transition"  data-live-search="true" multiple title="Choose City" data-size="7">
                            
    <option value="text">text</option>
    <option value="text2">text2</option>
    <option value="text3">text3</option>
                           
</select>
```

2. Introduce in the seach bar for example "aaaa"

3. The message of not found appears
4. Delete the text and select the option 1 ( text)
5. Click out 

The box won't hide

After some hours searching around and trying different solutions, i discover that this error is due to some js or css of the material kit , cause without it works fine.

I fix it temporally with this : 

``` js
$(document).click(function(event) {
    if(!$(event.target).closest('.selectpicker').length) { // it checks when it clicks out , more info here https://stackoverflow.com/questions/152975/how-do-i-detect-a-click-outside-an-element
        $('.bootstrap-select').removeClass("open"); // i remove this class to force to hide the box
        console.info("it get active");
    } 
```

I think this is not a perfect solution , cause it implies to have a function to check all the time if it clicks outside of it, i hope you can fix it in a more elegant way changing your code.

I hope is useful for some one else , regards

**Comment by groovemen** [comment]
Hello @robertofd1995,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
