### ISSUE TITLE
Missing !default in variables 

### ISSUE THREAD

**Issue by Camiloruiiz** [creativetimofficial/ct-material-kit-pro#101]
Line 22 and 24 _type.scss

**Comment by dragosct10** [comment]
Hi, @Camiloruiiz! Thank you for your observation. This issue affect your project? Regards, Dragos

**Comment by Camiloruiiz** [comment]
Hi, thank you for your reply and yes, I can't override the value, because it's getting the theme value instead of mine custom one.

**Comment by Camiloruiiz** [comment]
Ok thank you!
