### ISSUE TITLE
wrong img path

### ISSUE THREAD

**Issue by Camiloruiiz** [creativetimofficial/ct-material-kit-pro#102]
core/_carousel.scss 

<img width="1368" alt="screen shot 2018-05-11 at 15 55 40" src="https://user-images.githubusercontent.com/5870301/39930895-cf548872-5533-11e8-82f5-23b1e514c9b8.png">

**Comment by dragosct10** [comment]
Hi, @Camiloruiiz! Thank you for using our product. Did you use the latest version of the product 2.0.3? Regards, Dragos

**Comment by Camiloruiiz** [comment]
Yes, Im using that version, I just download from the cretive-tim page.

**Comment by dragosct10** [comment]
Hi, @Camiloruiiz! Please see this #63 issue to fix the problem. Regards, Dragos
