### ISSUE TITLE
Documentation Broken

### ISSUE THREAD

**Issue by 19peaches** [creativetimofficial/ct-material-kit-pro#103]
Hey Guys.

The documentation is broken, tons of 404's which stop a lot of the demos in the docs.

![screen shot 2018-05-12 at 6 22 11 am](https://user-images.githubusercontent.com/1456472/39957792-78840b74-55ad-11e8-9876-3b30f28d2af0.png)

**Comment by dragosct10** [comment]
Hi, @19peaches! Thank you for using our product. I just verified the documentation for the material kit pro 2.0.3 and it's working fine without any errors. Regards, Dragos

**Comment by octarino** [comment]
@dragosct10 The report Issue link in the documentation for material kit pro 2.0.3 gives a 404 error

**Comment by dragosct10** [comment]
Hi, @octarino! Sorry for the late response. Now the link it's fixed. Thank you for your observation. Regards, Dragos

**Comment by groovemen** [comment]
Hello @19peaches,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
