### ISSUE TITLE
animated cards keeps scale up on browser resize

### ISSUE THREAD

**Issue by fbacker** [creativetimofficial/ct-material-kit-pro#104]
**Specs:**
Material Kit Version: Using demo page
Browser: Google Chrome
OS: MacOS

**What happens:**
When resizing the browser, 'special' cards keeps getting bigger and bigger.

**What should happen:**
They should resize as a normal card e.g. 'Full Background Cards'

**Show it:**
- goto https://demos.creative-tim.com/material-kit-pro/index.html
- scroll down to 'Manual Rotating Cards'
- resize browser

**Comment by LambertStrategy** [comment]
Testing this out and confirm this is also occurring.

**Comment by dragosct10** [comment]
Hi! Thank you for using our product. We know about this issue and we are preparing an update in about 1-2 weeks for this product. Regards, Dragos

**Comment by fbacker** [comment]
Any progress on this?

**Comment by groovemen** [comment]
Hello guys,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
