### ISSUE TITLE
Scrolling issues on nav navbar-nav navbar-right on mobile

### ISSUE THREAD

**Issue by TheBeast762** [creativetimofficial/ct-material-kit-pro#105]
Hi,

My issue concerns the usage of the class nav navbar-nav navbar-right on mobile devices.
Both in simulating a mobile device on my pc and on an actual phone, these issues occur:

![img_3980](https://user-images.githubusercontent.com/27029259/40663640-698faf88-6359-11e8-8dcd-cec15cec63ec.PNG)
Here you can see that the user an scroll out of the navbar while it's still active

![img_3981](https://user-images.githubusercontent.com/27029259/40663644-69b8873c-6359-11e8-80db-9edbd928b9a9.PNG)
Here you can see that the user can scroll to the right towards non-existing space in the navbar

![screen shot 2018-05-29 at 15 50 48](https://user-images.githubusercontent.com/27029259/40663768-bb1dda78-6359-11e8-951b-4529908256d2.png)
Here the navbar in inactive

![screen shot 2018-05-29 at 15 50 36](https://user-images.githubusercontent.com/27029259/40663662-713ec192-6359-11e8-8c6d-b1d19ebb8e10.png)
Here the button activating the navbar is clicked on, but remains inactive

The code using the navbar:

![screen shot 2018-05-29 at 16 06 30](https://user-images.githubusercontent.com/27029259/40664031-4b26e204-635a-11e8-8768-d068b79e478e.png)

Thanks in advance! (sorry for the code picture, posting the code itself went wrong due to it containing single quotes, which cancel the code input on github)

**Comment by groovemen** [comment]
Hello @TheBeast762,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
