### ISSUE TITLE
dynamic shadows not usable with html srcset attribute

### ISSUE THREAD

**Issue by mvrska** [creativetimofficial/ct-material-kit-pro#106]
the srcset attribute of <img> is being used to serve the right sized image for the current device. Unfortunately since dynamic shadows only rely on the src attribute of <img> the produce their result, they either:

- load an extra image (extra bandwidth = bad) if the src tag is present and a different image size is used
- dont work at all

see [https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/](https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/) for additional info on srcset

**Comment by groovemen** [comment]
Hello @mvrska,

Thank you for using our products, I will ask you to check the **material-kit.js** file and go to line **119** and you will see the `initColoredShadows: function()` that generate the dynamic shadow. You can integrate if you wish the **srcset** attribute to the function and see if it works. 

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
