### ISSUE TITLE
Version 4.1... update is welcomed 

### ISSUE THREAD

**Issue by 262media** [creativetimofficial/ct-material-kit-pro#108]
> Wend can we expect  material kit pro updating to the latest release?
> 
> Regards
> Rui

# **v4.1 ship list** 
Highlights

Added new custom range form control.
Added new .carousel-fade modifier to switch carousel from slides to crossfade.
Added new .dropdown-item-text for plaintext dropdown items.
Added new .flex-fill, .flex-grow-*, and .flex-shrink-* utilities.
Added new .table-borderless variant for tables.
Added new .text-monospace utility.
Added new .text-body (default body color), .text-black-50 (50% opacity black), and .text-white-50 (50% opacity white) utilities.
Added new .shadow-* utilities for quickly adding box-shadows.
Added ability to disable Popper's positioning in dropdowns.
Heads up: updated Theming docs to confirm you cannot use CSS variables in media queries.
Split issue template into separate feature request and bug report templates, also adding a new GitHub support doc for coverage.
Fixed longstanding issue with Chrome rendering CSS columns incorrectly for cards.
Deprecate .text-hide—you'll see a warning during compilation.
Fixed up Dashboard and Offcanvas examples.
Breadcrumbs can now use non-string values as dividers.
CSS

#22799: Add .table-borderless option.
#22958: Add carousel fade option.
#22965: Add .dropdown-item-text to allow plaintext items in dropdown menu lists.
#24249: Add new responsive utilities, .w-auto and .h-auto.
#25197: Update .sr-only mixin and utility to remove clip-path that caused performance degradation. Matches changes to upstream H5BP.
#25248: Prevent word-wrap in progress bars.
#25333: Add ability to change .table-striped from odd or even via Sass variable.
#25356: Fix rounded corners on custom file in input group.
#25385: Add .flex-fill utility class. This was previously in our source code, and is mentioned in our navs docs, but was mistakenly dropped at some point.
#25386: Use variables for white and black in theme-color-level function.
#25400: Add basic position to dropup/right/left and dropdown-menu-right.
#25414: Override .custom-select's width in .form-inline.
#25503: Replace Unicode character in _hover.scss.
#25532: Fix pagination buttons hover z-index.
#25561: Create a variable for label margin bottom.
#25564: Use $input-bg for $custom-select-bg.
#25600: Add custom range input.
#25641: Make use of prefers-reduced-motion media query.
#25645: Disable link functionality on disabled btn-link.
#25657: Add variable, $table-caption-color, for table caption element.
#25672: Replace "loose" HEX values with their respective variables.
#25691: Add variable to handle the change of a modal border-radius.
#25736: Fix incorrect class .custom-file-control to .custom-file-label.
#25758: Add box-shadow utilities.
#25806: Collapse with flex elements.
#25807: Allow customization of breadcrumb border radius.
#25848: Removed commented out and useless navbar-align mixin.
#26172: Add .text-monospace utility.
#26168: Add new .flex-grow-* and .flex-shrink-* utilities.
#26169: Fix Chrome's rendering of .card-columns.
#26170: Additional text color utilities.
#26173: Deprecate .text-hide with @warn notice.
#25581: Allow non-string content as breadcrumb divider.

JS

#24092: Allow to disable Popper.js style for dropdowns.
#25218: Fix carousel transition duration.
#25219: Update dropdown to allow referenceElement.
#25398: Update jQuery to v3.3.1.
#25662, #25834: Variable transition durations
#25670: Remove unused variable.
#25671: Consistent usage of $(document.body) instead of $('body').
#25896: Use transitionEnd in QUnit since we moved away from PhantomJS
#25403: Dropdown - Skip element disabled via attribute when using keyboard navigation

# **v4.1.1 ship list**
Highlights

CSS

#25399, #26181: Add validation styles for file inputs.
#25453, #26193: Fix print color for dark tables.
#25717, #26416: Simplify custom file inner height for generated browse button.
#25944: Add workaround for IE to ensure custom check indicator appears properly.
#26242: Suppress text-hide deprecation warning with new mixin parameter so folks don't see this warning constantly.
#26269: Remove dialog from the HTML5 shim style as it was interfering with browser styles.
#26228, #26257: Replace Reboot monospace reset with system font stack, removing duplicate code from _code.scss.
#26232, #26238: Remove unnecessary resetting of left round of .custom-file-input:after.
#26300, #26313: Add cursor: pointer to carousel indicators.
JS

#25945: Improve v4 test coverage.
#26222: Clean up globals.
#26276: Small modal code optimization.
#26291: Fix issue related to Object.keys and Dropdown issue.

**Comment by 262media** [comment]
hello @timcreative team I can see a MK pro new release [2.1.0] 2018-06-29 and i'm wondering if you have tested against Bootstrap v4.1.1 ??!! There are important bug and compatibility fixes.

thanks in advance for your time
keep up the good work

**Comment by 262media** [comment]
Hi @dragosct10 sorry to bother but you seam the most active member ... do you guys plan to keep up testing against  the latest bootstrap releases?
Regards

**Comment by groovemen** [comment]
Hello @262media, 

Thank you for your interest in working with our products, we know about the latest version of Bootstrap Material Design but there were some incompatibilities and we decided to integrate it in the next update.

All the best, 
Stefan
