### ISSUE TITLE
Header 1 looks strange in Safari on iPhone

### ISSUE THREAD

**Issue by LarsGMortensen** [creativetimofficial/ct-material-kit-pro#111]
There’s a problem with the appearance of “header 1” in Safari on iPhone – not all elements are shown, and the raised background of the main-content is shown above the video.
Please see the attached screendump from [www.reklameafdelingen.dk](https://www.reklameafdelingen.dk/).
![header-looks-strange-reklameafdelingen](https://user-images.githubusercontent.com/26773745/41814177-08548cec-7746-11e8-91a2-d66e4df0939a.png)

**Comment by LarsGMortensen** [comment]
Hi Stefan

Thank you for reaching back to me.

I tried inserting the code.
It did not fix it (see the attached screendump - or simply try visiting <http://www.reklameafdelingen.dk> from an iphone)


Med venlig hilsen
Lars Grove Mortensen

Brøndshøjvej 11
8740 Brædstrup
Danmark

Tlf: 25 31 79 01
E-mail: <lars@grove-mortensen.dk>
Web: <http://www.grove-mortensen.dk>



Den 27. juni 2018 kl. 11.24.27 +02.00, skrev Stefan <notifications@github.com>:

**Comment by LarsGMortensen** [comment]
Also... why doesn't the Bootstrap responsive-embed CSS work with your material kit?

<https://getbootstrap.com/docs/4.1/utilities/embed/>


I found a down-and-dirty alternative way of doing it right here:
<https://blog.theodo.fr/2018/01/responsive-iframes-css-trick/>
...and that does work.

But I would rather use the native Bootstrap way of doing it - but it seems that you have taken that out of the Bootstrap CSS?


Med venlig hilsen
Lars Grove Mortensen

Brøndshøjvej 11
8740 Brædstrup
Danmark

Tlf: 25 31 79 01
E-mail: <lars@grove-mortensen.dk>
Web: <http://www.grove-mortensen.dk>



Den 27. juni 2018 kl. 11.24.27 +02.00, skrev Stefan <notifications@github.com>:

**Comment by groovemen** [comment]
We are currently working on an update for this product, we'll fix this issue too. Stay tuned

**Comment by groovemen** [comment]
Until then, try to set this property: `height: calc(100vh + 270px);` for the `page-header` class on the same max-weight.

**Comment by groovemen** [comment]
Hello @LarsGMortensen,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
