### ISSUE TITLE
gulp scss compilation not working

### ISSUE THREAD

**Issue by yogiis98** [creativetimofficial/ct-material-kit-pro#113]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by rsuard** [comment]
Hello there, 

Sorry I 'm new using SCSS, I used LESS for a few times. (But I use node and NPM for some other reasons so I understand the processes)

I followed your docu steps : 

> Download the project’s zip.
> Make sure you have node.js (https://nodejs.org/en/) installed.
> Type npm install in terminal/console in the source folder where package.json is located.
> Run in terminal gulp open-app for opening the Kit Page (default) of the product. You can set in gulpfile.js from your downloaded archive any page you want to open in browser, at line 30: gulp.src('presentation.html').
> Run in terminal gulp compile:scss for a single compilation or gulp watch for continous compilation of the changes that you make in *.scss files. This command should be run in the same folder where gulpfile.js and package.json are located.

I have some troubles at this point on my Mac : 
1- After running "npm install" in the right folder, I got some WARN (down this post)
2- Gulp is not found then  : 
`gulp open-app
-bash: gulp: command not found`
3- I tried to install gulp 4 by using npm i gulp and got some other WARN (down this post 2)

I m thinking there is some trouble with older version of gulp (deprecated) and natives, minimatch, graceful-fs .

Questions : 
How to update these ? (I tried npm i natives, npm i minimatch, npm i graceful-fs) 
Do I need to use SUDO to upgrade those ? 
Does I need to have Gulp 4 ? 
How can I install properly gulp to compile and watch SCSS ?

Thanks a lot, 
BR,

Romain 

**WARN 1 Install**
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> node-sass@4.12.0 install /Users/rsuard/Dropbox (FCMS)/Lab/200-Projets en cours/3DImmo-demo/material-kit-pro-html-v2.1.1/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/rsuard/.npm/node-sass/4.12.0/darwin-x64-64_binding.node

> node-sass@4.12.0 postinstall /Users/rsuard/Dropbox (FCMS)/Lab/200-Projets en cours/3DImmo-demo/material-kit-pro-html-v2.1.1/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/rsuard/Dropbox (FCMS)/Lab/200-Projets en cours/3DImmo-demo/material-kit-pro-html-v2.1.1/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN material-kit-pro@2.1.0 No repository field.
npm WARN material-kit-pro@2.1.0 license should be a valid SPDX license expression


**WARN 3 Gulp**
npm i gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN material-kit-pro@2.1.0 No repository field.
npm WARN material-kit-pro@2.1.0 license should be a valid SPDX license expression

+ gulp@3.9.1
updated 1 package and audited 2183 packages in 4.205s
found 7 vulnerabilities (1 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by groovemen** [comment]
Hello @rsuard, 

Thank you for using our products, it's weird that it doesn't work for you. I will ask you to uninstall the gulp `npm uninstall -g gulp ` and then please try to install it again. It should work with no problem.

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by rsuard** [comment]
Hello Stefan @groovemen,

Thanks for your answer, I m, badly, still on the same spot.
I ve uninstall gulp (which I thought was not properly install as you thought too)
Then tried to install it properly, and failed again :-( 
see the log down there,  (I sudo it because first time it told me there might be permission issues)

What do you think I can do ?

Thanks, BR,
Romain

---- terminal logs : 
FI013159:material-kit-pro-html-v2.1.1 rsuard$ sudo npm uninstall -g gulp
up to date in 0.032s
FI013159:material-kit-pro-html-v2.1.1 rsuard$ sudo npm install gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN material-kit-pro@2.1.0 No repository field.
npm WARN material-kit-pro@2.1.0 license should be a valid SPDX license expression

+ gulp@3.9.1
updated 1 package and audited 2183 packages in 3.39s
found 7 vulnerabilities (1 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by rsuard** [comment]
PS : I am on a this year iMac on Catalina.

**Comment by groovemen** [comment]
I will ask you to install the LTS version of node.js: https://nodejs.org/en/ and please try again and let us know if it worked. 

Best.
Stefan
