### ISSUE TITLE
On Internet Explorer, Material Kit Pro 2.1 card-profile works fine but card-product looks very odd with tall shadow

### ISSUE THREAD

**Issue by weblackey** [creativetimofficial/ct-material-kit-pro#114]
Yes, running latest Material Kit Pro 2.1.0 

# Expected Behavior

Expecting the image in card-blog and card-product to look normal like in card-profile

# Current Behavior

the image in card-blog and card-product looks like it has a very tall shadow below it

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. simply look at your own components list using Internet Explorer (not Edge)

https://demos.creative-tim.com/material-kit-pro/index.html

then select components and scroll down to the cards

2. check card-profile, it's ok
3. check card-blog, 
not  ok

See attached screenshots
![materialkitblogcard](https://user-images.githubusercontent.com/31600102/42423151-e3df4456-82e4-11e8-91a7-0a694cbc0853.jpg)
![materialkitprofilecard](https://user-images.githubusercontent.com/31600102/42423154-ee0cd010-82e4-11e8-9e7b-97c74265034d.jpg)

**Comment by groovemen** [comment]
Hello @weblackey, Thank you for your interest in working with our products and also for letting us know about this issue. All you have to do is to set the **min-height: 215** for the card-header-image div.

```
@media screen and (min-width: 767px) {
    .card .card-header-image {
        max-height: 215px;
    }
}
```

*this will be fixed in the next update

Best, 
Stefan

**Comment by groovemen** [comment]
Hello again, I found a better solution to solve this issue:
 
You can detect the browser by a media query and set a property just for IE:
```
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  .card{
    display: inline-block;
  }
}
```

this will overwrite the **display: flex;** on `.card` property that brokes the card-header-image (shadow).

Regards, Stefan

**Comment by weblackey** [comment]
Thank you so much for the reply!

**Comment by weblackey** [comment]
Hi Stefan, thanks again for your followup

 

This is indeed a much better solution

 

One thing we were worried about with the previous solution was that it might prevent fluid resizing on phones and tablets if necessary, and also we wanted to keep shadows if possible

 

I have to say that we’re so happy with your Material Kit template in general that we purchased your big bundle just to reward you even though we didn’t have an immediate need for additional templates yet.

 

We will submit our web site www.sharxsecurity.com to your gallery

 

Best Regards

**Comment by weblackey** [comment]
I am very happy with the support that was provided and I am ready to close the issue. I just have one followup question that may be obvious to you but I'm kind of struggling with it. After implementing your solution it seems we're missing shadows from the product cards. Our products are white so the shadows on the cards would help to break up the monotony of white on white. 

Here is a snapshot from our home page on www.sharxsecurity.com where we use your profile cards to get nice shadows:

![materialkitniceshadows](https://user-images.githubusercontent.com/31600102/42487771-05c9747a-83f2-11e8-87be-74429f91ad4f.jpg)

But here is what our product cards look like after the fix for the incredibly long shadows:

![materialkitshadowsdisappeared](https://user-images.githubusercontent.com/31600102/42487790-225d8acc-83f2-11e8-8668-8f05c7ea65a1.jpg)

I found that if I add img-raised and rounded it helps improve the looks:

![materialkitshadowsraisedimg](https://user-images.githubusercontent.com/31600102/42487820-3c4e4c6e-83f2-11e8-8850-6c96857af19a.jpg)

I'm wondering if there is a better solution to get the shadows on the product cards to look more like the profile cards, or whether the solution I found with img-raised is what we should implement. Right now it is implemented only on the first card at the bottom of http://www.sharxsecurity.com/product_HTNC4403DM.html

Thanks!

**Comment by groovemen** [comment]
Hello there,

After taking a look over your project, I noticed that you missed the set some classes (**.img .img-fluid .img-raised .rounded**) for the images.

After you set these classes your cards will look like this:
<img width="1375" alt="screen shot 2018-07-11 at 11 23 20" src="https://user-images.githubusercontent.com/21063398/42559641-5b738594-84fd-11e8-9283-913c1b27651e.png">
I must say nice work on your project! Good job!

Best, 
Stefan

**Comment by weblackey** [comment]
Thanks so much, yes we had purposely only modified one of the cards to show you what it would look like with and without the img-raised. Just wanted to check with you to see if img-raised would be your recommendation for creating shadows as well, or if there was an even better solution that could result in the stronger shadows like in the cards below.
![materialkitniceshadows](https://user-images.githubusercontent.com/31600102/42738717-ee0e763e-8877-11e8-97be-64f6b8fbe207.jpg)

In any event the original issue is fixed so I'm closing this case.
