### ISSUE TITLE
TypeError when using an achor element to open a tab from within another tab

### ISSUE THREAD

**Issue by Fokuseret** [creativetimofficial/ct-material-kit-pro#117]
# Expected Behavior

I've added an anchor element inside the initially-active tab, which once clicked, would ideally switch to another tab. My setup is as follows:

```
<div class="card card-nav-tabs card-plain">
    <div class="card-header card-header-danger">
        <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
                <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="nav-item">
                        <a class="nav-link active" href="#home" data-toggle="tab">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#updates" data-toggle="tab">Updates</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#history" data-toggle="tab">History</a>
                    </li>
                </ul>
            </div>
        </div>
    </div><div class="card-body ">
        <div class="tab-content text-center">
            <div class="tab-pane active" id="home">
                <p>Initially-active tab's content</p>

                <!-- This is my inner anchor element -->
                <a class="nav-link" href="#updates" data-toggle="tab">Switch to updates</a>
            </div>
            <div class="tab-pane" id="updates">
                <p>Second tab's content</p>
            </div>
            <div class="tab-pane" id="history">
                <p>Third tab's content</p>
            </div>
        </div>
    </div>
  </div>
```

# Current Behavior

Upon clicking my anchor element, the tab switching behaviour is not triggered.

# Failure Information (for bugs)

The browser's console reveals a **TypeError: container is undefined** JavaScript error, triggered by the `_proto._activate` method at line 3264 within **bootstrap-material-design.js**

My JavaScript skills are not so extended, therefore I'm unable to figure out a viable solution to this issue. Any pointers would be highly appreciated.
/Fokuseret

**Comment by groovemen** [comment]
Hello @Fokuseret, 

Thank you for your interest in working with our products, I just made you a structure of nav tabs, check the file from below an try to integrate it in your project. 

[card w/ tabs.html.zip](https://github.com/creativetimofficial/ct-material-kit-pro/files/2208864/card.w.tabs.html.zip)

Please let us know if this worked for you. 

All the best, 
Stefan

**Comment by Fokuseret** [comment]
Hey @groovemen,

Thanks so much for your fast reply. I tried to implement the solution that you suggested into the main index.html file of the Material Kit Pro, the one that comes with the product by default. A closer look revealed the fact that your provided solution is using exactly the same approach as I was using. As a consequence, the problem doesn't seem to be fixed. Please check out the attached screenshot below for further details related to the error that I'm encountering.

![js-error](https://user-images.githubusercontent.com/25161888/43039699-42270f5a-8d33-11e8-8ca8-e1ec46a8190a.png)

Thanks a lot for your efforts and of course for an outstanding product.
/Fokuseret

**Comment by groovemen** [comment]
Hello again @Fokuseret, 

Please remove the **data-toggle="tab"** from your anchor element.  Let me know if it works. 
Best, 
Stefan

**Comment by Fokuseret** [comment]
Hi @groovemen,

I removed the `data-toggle="tab"` attribute as per your suggestion, and I noticed the fact that there are no more errors in the browser's console. However, nothing happens when the link is clicked. Just to confirm, I'm still using the sample file (index.html) that comes with the product by default.

Any further ideas?

Thanks a lot.
/Fokuseret

**Comment by groovemen** [comment]
Please make sure that you didn't miss anything, I double checked the problem but everything looks good. Check the following video.

[video.zip](https://github.com/creativetimofficial/ct-material-kit-pro/files/2219282/tabs.zip)

Best, 
Stefan

**Comment by Fokuseret** [comment]
Thank you for taking your time to look into this matter @groovemen. 

In the video that you attached above, I can't see the functionality that I'm aiming to achieve. I can see that the tabs are properly switching when you click the navs, and that indeed **does work** for me, but this is not my problem. My problem is that **nothing** happens when you click the "SWITCH TO UPDATES" anchor. I'm afraid I haven't explained it properly, and probably rather focused on explaining the problem that I'm encountering. Apologies for that, and let me explain it in a better way - and please check out the code I'm using within the HTML file that I'm attaching below for your convenience (it's a copy of the index.html file where I removed all the non-essential code from) :)

[tabs-issue.html.zip](https://github.com/creativetimofficial/ct-material-kit-pro/files/2219522/tabs-issue.html.zip)

What I'm trying to build, is just an anchor element that would be included within one of the tabs. Once that anchor is clicked, it would ideally make the **tabs-card element** switch to a different tab, that is, the tab that is assigned to that anchor element within its href attribute - as per my current setup, it is the second tab. Please note that as soon as you add the data-toggle="tab" attribute to the anchor element, the JS error I was describing in one of my previous posts will be shown in the browser's console.

Once again, many thanks for your time and efforts, they're greatly appreciated.
/Fokuseret

**Comment by Fokuseret** [comment]
Any ideas on this matter, @groovemen? I found a [similar issue](https://github.com/twbs/bootstrap/issues/18409) with Bootstrap 4 that was fixed meanwhile.

As far as Material Kit Pro goes, is it something that can be fixed? I would highly appreciate a positive resolution on this matter, as my setup greatly depends on such a feature. At the risk of repeating myself, I'm not very skilled in JS, but I would appreciate if you could at least provide me with a solid starting point, should a quick-n-dirty solution was not available at this moment.

Thank you.
/Fokuseret

**Comment by Fokuseret** [comment]
@timcreative is there any chance of having this issue figured out? Otherwise I might just end up paying a frontend dev freelancer to fix it for me. I would, however, appreciate an answer on this matter.

Thank you.
/Fokuseret

**Comment by groovemen** [comment]
Hello again, 

Do you have figured out about your issue by switching the tabs? I reproduced again the problem and also tested your file **tabs-issue.html** and noticed that you have errors in console.

Best, 
Stefan
