### ISSUE TITLE
card-header-primary color hard-coded to purple

### ISSUE THREAD

**Issue by tesujimath** [creativetimofficial/ct-material-kit-pro#118]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Changing the primary color should change the card-header-primary from purple

# Current Behavior

card-header-primary is purple

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

In my SASS before importing material-kit, I do this:
```
$teal-500: #009688 !default;
$teal: $teal-500 !default;
$brand-primary: $teal !default;
```

I observe the card-header-primary stays purple, because of these lines in `_cards.scss`:
```
    .card-header-primary,
    &.bg-primary,
    &.card-rotate.bg-primary .front,
    &.card-rotate.bg-primary .back{
      background: linear-gradient(60deg, $purple-400, $purple-700);
    }
```
I fixed it by appending my own override later:
```
.card {
    .card-header-primary,
    &.bg-primary,
    &.card-rotate.bg-primary .front,
    &.card-rotate.bg-primary .back{
      background: linear-gradient(60deg, $teal-400, $teal-700);
    }
}
```

But this is not a real solution.  Perhaps your SASS should say $primary-400 and $primary-700, for example?  It seems there is more to changing the brand color than this.  Is there some documentation on what else may be required?

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @tesujimath, thank you for using our products, did you have changed the **brand.scss** file from the _variables_ folder? If not, please make this changes and let us know if it worked. Best, Stefan

**Comment by tesujimath** [comment]
Hi @groovemen Yes, I already tried that.  It has no effect, because your SASS in _cards.scss uses hard-coded purple, rather than $brand-primary, as per my comment above.

**Comment by groovemen** [comment]
We will fix this issue into the next update; sorry for the inconvenience. 
All the best, 
Stefan
