### ISSUE TITLE
MODAL - INCORRECT BEHAVIOR

### ISSUE THREAD

**Issue by mohammedtantawy6102** [creativetimofficial/ct-material-kit-pro#119]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
--> Login Modal button working normally like it does in the documentation

# Current Behavior
What is the current behavior?
--> The website break. It freezes, I can't click anything in the page. I've tried to use both the one in the documentation and the one on the bootstrap4 website.

# Failure Information (for bugs)
--> In the inspector it doesn't give any error.

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
--> 1. Copy any code from here (I'm interested in the login modal) 
https://demos.creative-tim.com/material-kit-pro/docs/2.0/components/modal.html
2. Paste in an HTML page with the starter template 
3. The page breaks

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: MacBook Pro
* Operating System: High Sierra 10.13.6
* Browser and Version: Google Chrome Version 68.0.3440.106 - Safari 11.1.2

## Failure Logs

Please include any relevant log snippets or files here.
--> Page freeze. Can't scroll up down, can't click on anything. In the inspector, it doesn't give any messages. The only thing possible is to reload the page but the behavior repeats.

Thanks

**Comment by groovemen** [comment]
Hello @mohammedtantawy6102,

Thank you for using our products, I checked the behavior of the modal in the starter-template: [test.html.zip](https://github.com/creativetimofficial/ct-material-kit-pro/files/2322969/test.html.zip) and it worked perfectly. All you have to do is to move outside of the `<div class="main main-raised">` your modal content. You have an example in the file attached above.

All the best, 
Stefan
