### ISSUE TITLE
[Request] desktop off-canvas menu

### ISSUE THREAD

**Issue by osc2nuke** [creativetimofficial/ct-material-kit-pro#122]
Request to get the canvas on desktop and tablet/mobile viewports.
open Menu on the LEFT, open CART on the right.
Both already collapsed show?
![screencast-shisha taxi-2018 09 11-19-03-44](https://user-images.githubusercontent.com/5169035/45376094-3b39e680-b5f7-11e8-92b6-8b9c3ee6dab4.gif)

**Comment by groovemen** [comment]
Hello @osc2nuke,

Thank you for using our products, from what I see above you already set your project to have responsive functionalities on the desktop viewport, so I will ask you to give us more details about your issue. 
Please let us know if we can help you with anything else.

All the best,
Stefan
