### ISSUE TITLE
Mixed http and https content errors

### ISSUE THREAD

**Issue by godrunner** [creativetimofficial/ct-material-kit-pro#127]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by godrunner** [comment]
Greetings!!
I am enjoying Creative Kit Pro. Nice work!
I am having one issue.
If I publish to server that has SSL/HTTPS enabled, there are a few JavaScript errors on the console indicating mixed content. (at least in Chrome and Edge / http and https mixed content) If in .Net Core, the fonts and material icons really do get blocked and the site does not display properly. Do you guys know where this mixed content is coming from and how to fix it? I don’t see the source of it right off. 

You can see the exact same errors on a page on your server like this. 
https://demos.creative-tim.com/material-kit-pro/examples/about-us.html
Mixed Content: The page at 'https://demos.creative-tim.com/material-kit-pro/examples/about-us.html' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/rosarivo/v1/OGdIq-p0tOtBN2VMVvO9W_esZW2xOQ-xsNqO47m55DA.woff'. This request has been blocked; the content must be served over HTTPS.

I see no direct links to http://themes.googleusercontent.com and all the google links are initiated with https.

**Comment by groovemen** [comment]
Hello @godrunner,

Thank you for using our products and for your good thoughts; I will ask you to point us where the insecure fonts were requested. 

All the best, 
Stefan

**Comment by godrunner** [comment]
Sorry, I did not notice the reply here. This still shows up all over on your site. 
As mentioned above, like here:
https://demos.creative-tim.com/material-kit-pro/examples/about-us.html

**Comment by godrunner** [comment]
@groovemen, see above.
