### ISSUE TITLE
Non-responsive <H1>

### ISSUE THREAD

**Issue by LarsGMortensen** [creativetimofficial/ct-material-kit-pro#128]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The theme is responsive. So I would expect that the headers would be responsive as well.

# Current Behavior

The H1 heading is not responsive - so when you have long words in there; it looks undesireable on phones and other small screensizes.
But I may have found a solution that you can use as inspiration - please see this screencast video:
https://www.screencast.com/t/6TsdKRIC

**Comment by groovemen** [comment]
Hello again @LarsGMortensen,

Thank you for using our products, we will fix this issue in the following update. Thank you for your feedback. 

All the best, 
Stefan
