### ISSUE TITLE
Wrong width on example page "contact us"

### ISSUE THREAD

**Issue by LarsGMortensen** [creativetimofficial/ct-material-kit-pro#129]
# Expected Behavior

I would expect that the entire team would have the same page width - so that you would be able to build an entire coherent site with it.

# Current Behavior

The page width on the example page "contact us" has a different width than all the other pages. This is due to a max-width of 970px on the container on that page.
See video explanation for further details: https://www.screencast.com/t/4CmIyAbIEMiU

Note: I used your own example site to demonstrate, to eliminate any errors caused by my own site.

**Comment by groovemen** [comment]
Hello @LarsGMortensen, 

Thank you for using our products, all you have to do is to erase the style `max-width: 970px;` from the container of the contact-us page. It was set on purpose the width to have a different page design.

All the best, 
Stefan
