### ISSUE TITLE
Navbar-collapse bug fix on IE 11

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/ct-material-kit-pro#13]
Hi! On IE 11 we have an issue with navbar-collapse. If you are on responsive mode the all navbar it is not visible. To fix this issue please take the file that I will upload here and just replace the `_responsive.scss` file with the new one. After that you must compile your scss with [Koala](koala-app.com). Please make sure that you're output path is `HTML/assets/css/material-kit.css`.

[_responsive.scss.zip](https://github.com/creativetimofficial/material-kit-pro/files/974040/_responsive.scss.zip)

Regards,
Dragos

**Comment by mkarnicki** [comment]
It's not even only on IE 11, it affects Chrome and probably the rest of the browsers too.

Man, I spent hours debugging this today. Thank you for the patch. CreativeTim, you guys should apply this ASAP!!!
