### ISSUE TITLE
Feature request: EU Cookie warning

### ISSUE THREAD

**Issue by LarsGMortensen** [creativetimofficial/ct-material-kit-pro#130]
As you probably know: All websites serving users in the EU must show a cookie warning. Thus, it would be nice if your theme(s) would include this cookie-warning.

**Comment by groovemen** [comment]
Hello @LarsGMortensen, 

Thank you for your interest in working with our products and for letting us know about the cookie-warning integration; I will talk with the team and probably if it will be more users that need this feature, in the next updates we will integrate it in our products.

All the best, 
Stefan
