### ISSUE TITLE
Wrong width on example page "product page"

### ISSUE THREAD

**Issue by LarsGMortensen** [creativetimofficial/ct-material-kit-pro#133]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I would expect that the theme would have a consistent look across all pages.

# Current Behavior

The example page "product page" has a different width (on the primary content, on the top navbar, on everything) than all other pages.

**Comment by LarsGMortensen** [comment]
https://www.dyrecentret.dk/butik/test-produkt-1-prd2.html

**Comment by groovemen** [comment]
Your code structure for the Product Page should look like this:

```
<div class="main main-raised">
  <div class="container">
    <div class="section">
    --- your content ---
    </div>
  </div>
</div>
```

after that you should erase from the `assets/scss/material-kit/_example-pages-extend.scss` at line 410:     
```
.main-raised {
   margin: -40vh 0px 0px;
   padding: 40px;
}
```
after that the page will look like this:

<img width="1440" alt="screenshot 2018-11-16 at 18 54 32" src="https://user-images.githubusercontent.com/21063398/48635547-23088e00-e9d1-11e8-8c6c-beff93e03708.png">


Hope that information helps you.
All the best, 
Stefan
