### ISSUE TITLE
DateTimePicker Bootstrap 4 compatible

### ISSUE THREAD

**Issue by rlblanco** [creativetimofficial/ct-material-kit-pro#135]
I'm using Material Kit Pro. I've found an update for eonasdan-datetimepicker which is implemented in this kit.

New version of DateTimePicker supports Bootstrap 4. Eonasdan version don't. (see [https://stackoverflow.com/questions/47618134/bootstrap-datetimepicker-for-bootstrap-4])

I've tried the new version of the DateTimePicker  [https://tempusdominus.github.io/bootstrap-4/] with Material Kit Pro but is having problems with the object .dropdown-menu.bootstrap-datetimepicker-widget: calendar becomes transparent and it doesn't show.

Are there any chance Material Kit Pro to be updated?

**Comment by groovemen** [comment]
Hello @rlblanco, 

Thank you for using our products, we know about that new version for BS4 of the datetimepicker but we will integrate it into our product in the next update. Sorry for the inconvenience. Please let us know if we can help you with anything else.

All the best, 
Stefan
