### ISSUE TITLE
Update devDependancies 

### ISSUE THREAD

**Issue by estaten** [creativetimofficial/ct-material-kit-pro#136]
# Update devDependencies:

 === npm audit security report ===

# Run  npm install --save-dev gulp@4.0.0  to resolve 5 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change

  High            Regular Expression Denial of Service

  Package         minimatch

  Dependency of   gulp [dev]

  Path            gulp > vinyl-fs > glob-stream > glob > minimatch

  More info       https://nodesecurity.io/advisories/118

  High            Regular Expression Denial of Service

  Package         minimatch

  Dependency of   gulp [dev]

  Path            gulp > vinyl-fs > glob-stream > minimatch

  More info       https://nodesecurity.io/advisories/118

  High            Regular Expression Denial of Service

  Package         minimatch

  Dependency of   gulp [dev]

  Path            gulp > vinyl-fs > glob-watcher > gaze > globule > glob >
                  minimatch

  More info       https://nodesecurity.io/advisories/118

  High            Regular Expression Denial of Service

  Package         minimatch

  Dependency of   gulp [dev]

  Path            gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch

  More info       https://nodesecurity.io/advisories/118

  Low             Prototype Pollution

  Package         lodash

  Dependency of   gulp [dev]

  Path            gulp > vinyl-fs > glob-watcher > gaze > globule > lodash

  More info       https://nodesecurity.io/advisories/577

# Run  npm install --save-dev gulp-open@3.0.1  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change

  Critical        Command Injection

  Package         open

  Dependency of   gulp-open [dev]

  Path            gulp-open > open

  More info       https://nodesecurity.io/advisories/663

found 6 vulnerabilities (1 low, 4 high, 1 critical) in 2318 scanned packages
  6 vulnerabilities require semver-major dependency updates.

# Solution  

 {
  "name": "material-kit-pro",
  "description": "Premium Bootstrap 4 Material Design",
  "version": "2.1.0",
  "homepage": "http://creative-tim.com/product/material-kit-pro",
  "author": "Creative Tim",
  "license": "Creative Tim License <www.creative-tim.com/license>",
  "devDependencies": {
    **"gulp": "^4.0.0",** (current)
    "gulp-autoprefixer": "^4.1.0",
    "gulp-clean": "^0.3.2",
    "gulp-install": "^1.1.0",
   **"gulp-open": "^3.0.1",** (current)
    "gulp-sass": "^3.1.0",
    "gulp-sourcemaps": "^2.6.3"
  }
} #

**Comment by groovemen** [comment]
Hello @estaten, 

Thank you for using our products, we will update the dependencies in the next update. 
Best, Stefan
