### ISSUE TITLE
Feature request: Auth workflow pages

### ISSUE THREAD

**Issue by thclark** [creativetimofficial/ct-material-kit-pro#137]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected behaviour

The kit provides `LoginPage` and `SignupPage`, which is only a fraction of full user auth workflow. To complete that workflow, it would be great if we had the following views:
- `PasswordResetRequestPage` (*"please enter your email to reset password"*)
- `PasswordResetRequestedPage` (*"Thanks! If **email** has an account, we'll send a password reset link. Check your mail!"*)
- `PasswordResetSucceededPage` (*"congrats, your password has been reset, click here to login"*)
- `PasswordResetFailedPage` (*"oops, something went wrong resetting your password. Perhaps your link expired? Click here to try again"*)

N.B. I actually currently do this all with one component, a `PasswordResetPage`, whose props determine which of those views it shows. This could work well too :)

# Current behaviour

Only `LoginPage` and `SignupPage` are present.

I hope this is helpful! :)

**Comment by groovemen** [comment]
Hello @thclark, 

Thank you for using our products, for your feedback and for your suggestion. I will talk with my colleagues and probably we'll integrate into the next update these pages.

 Please let us know if we can help you with anything else.

All the best,
Stefan
