### ISSUE TITLE
Error in css map

### ISSUE THREAD

**Issue by dustingraves** [creativetimofficial/ct-material-kit-pro#139]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I just updated from 2.1.0 to 2.1.1 and it shouldn't be throwing an error about css

# Current Behavior
```
 ERROR `/assets/css/kit-pro.css.map' not found.
 ```
# Failure Information (for bugs)

`material-kit.css.map`:
```javascript
{
	"version": 3,
	"file": "kit-pro.css", //this seems to be the problem
	"sources": [
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

Although I am running it through a template engine the problem is a file reference
1. Run with jekyll serve
2. See error

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Macbook Pro
* Operating System: OS X Mojave
* Browser and Version: Chrome Latest

## Failure Logs

```
gorillagive.github.io git:(material-ui) ✗ bundle exec jekyll serve
Configuration file: /_config.yml
            Source: /
       Destination: /_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 4.361 seconds.
 Auto-regeneration: enabled for '/'
    Server address: http://127.0.0.1:4000//
  Server running... press ctrl-c to stop.
[2018-12-19 12:00:41] ERROR `/assets/css/kit-pro.css.map' not found.
```

**Comment by groovemen** [comment]
Hello @dustingraves, 

Thank you for using our products and for letting us know about this issue; until the next update I will ask you to make the following change to solve this problem:

- go to the **material-kit.css** file to the line 22311 and replace the` # sourceMappingURL=kit-pro.css.map` even it's commented with this one: `# sourceMappingURL=material-kit.css.map `.

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
