### ISSUE TITLE
card-rotate height problem

### ISSUE THREAD

**Issue by ihuangmx** [creativetimofficial/ct-material-kit-pro#141]
Hi, I found that in card rotate mode, If there is too much content in card back,when you click the 'back' to show the back card, the content of back card will exceed the size of the card container. So how can I solve this problem ?

**Comment by groovemen** [comment]
Hello @ihuangmx, 

Thank you for using our products, all you can do is to set a property `height: 100vh;` for the **.back** class. 

Best, Stefan
