### ISSUE TITLE
File upload data not submitting

### ISSUE THREAD

**Issue by AppyCat** [creativetimofficial/ct-material-kit-pro#142]
Hi, I purchased Material Kit Pro for Bootstrap 4.

When I try to use the file upload component, it reads the file but is not passing the path to the file.

As a result on the receiving end the file shows up as nil in the db. When I select the file, the name of the file shows up. On upload file is not being sent, the name of file is sent as a param, but not the file data.

I'm using Ruby on Rails, it usually creates a tmp version of the file and then resizes. However in this case it is not receiving the file at all on upload. I am using the file upload listed on the forms section, not the Jasny file uploader.

Here's my code:
[form.txt](https://github.com/creativetimofficial/material-kit/files/2843999/form.txt)

Its sending file name, but not file data.

I am using Material Kit PRO - v2.1.1

**Comment by groovemen** [comment]
Hello @AppyCat,

Thank you for using our products, unfortunately, we don't make the backend for this products so we can't help you with this issue so I will ask you to open an issue [on the plugin's repository](https://github.com/jasny/bootstrap/issues) on Github. Also you can check the full documentation of this plugin here: http://www.jasny.net/bootstrap/ 

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by AppyCat** [comment]
Hi Stefan,

Thank you for your reply.

Its for the regular file uploader, not the Jasny file uploader.

I am not using the Jasny plugin at all. The file uploader detailed on the forms page of the docs sends the file name, but not the binary file data.

Any idea what may be causing that?

Best,
Pardeep.

**Comment by AppyCat** [comment]
Thank you for your reply.

Its for the regular file uploader, not the Jasny file uploader.

I am not using the Jasny plugin. I am using the file uploader that has a paper clip icon button.

The regular non-Jasny file uploader detailed on the forms page of the docs sends the file name, but not the binary file data. This is your url for the 3 examples of file uploading, about half way down the page:

https://demos.creative-tim.com/material-kit-pro/docs/2.1/components/forms.html#examples

Any idea what may be causing that? As this is not the Jasny component, I'm not sure where else to reach out.

**Comment by groovemen** [comment]
We are just using the Bootstrap's default file upload: https://getbootstrap.com/docs/4.2/components/input-group/#custom-file-input so you have to create the function that parses and moves it into your DB.

**Comment by AppyCat** [comment]
I am using the example on your docs. I have a function that grabs the data and stores it in the db. That works fine with a regular html file input.

However when I use the example on your docs, it sends the file name, but not the file data. Some issue between:

inputFileVisible   and
inputFileHidden

The inputFileVisible does not send the binary data to inputFileHidden

Have you actually got this working in any production use case?

Here is the code on the docs example:

<div class="form-group form-file-upload form-file-multiple">
    <input type="file" multiple="" class="inputFileHidden">
    <div class="input-group">
        <input type="text" class="form-control inputFileVisible" placeholder="Single File">
        <span class="input-group-btn">
            <button type="button" class="btn btn-fab btn-round btn-primary">
                <i class="material-icons">attach_file</i>
            </button>
        </span>
    </div>
  </div>

**Comment by groovemen** [comment]
Please try this function to get the path of the file: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_fileupload_value to get the path for the file that you want to upload. Here you can find more resources: https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/intro_input.html. 
If you try the [Bootstrap default upload input](https://getbootstrap.com/docs/4.2/components/input-group/#custom-file-input), it works fine?

**Comment by AppyCat** [comment]
Thanks, I will try that. The goal is to use a material design file input.

Have you got the example in your documentation to work?
