### ISSUE TITLE
Bootstrap Select plugin is sized inconsistently relative to standard inputs

### ISSUE THREAD

**Issue by estianross** [creativetimofficial/ct-material-kit-pro#144]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [YES] I am running the latest version
- [YES] I checked the documentation and found no answer
- [YES] I checked to make sure that this issue has not already been filed
- [YES] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Bootstrap Select plugin provided must have the same exact display size as other inputs so when placed horizontally (for example in grid layout when creating form) there is no visual inconsistency.

# Current Behavior

Bootstrap Select plugin provided is sized slightly larger than standard inputs provided which results in very jarring visual inconsistency. As seen from the example in documentation provided and on a self created form.
![screenshot_2019-03-05 material kit pro by creative tim](https://user-images.githubusercontent.com/27760780/53785079-f9438a80-3f1f-11e9-8492-7049e3496a93.png)
![screenshot_2019-03-05](https://user-images.githubusercontent.com/27760780/53785087-ff396b80-3f1f-11e9-8eeb-332389aedb6a.png)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Laptop (Lenovo Y-700)
* Operating System: Ubuntu 18.04
* Browser and Version: Latest Chrome and Firefox

**Comment by estianross** [comment]
Issue resolves if the following is added to an override stylesheet
`.btn-group, .btn-group-vertical {
    position: relative;
    margin: 0 !important;
}`

**Comment by iagofrota** [comment]
I'm going through the same problem!

**Comment by groovemen** [comment]
Hello guys, 

Thank you for using our products, here is a simple fix for this issue, until the next update: 
you have to set for the **selectpicker** (.select-with-transition) a `margin-top: 10px;`

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by iagofrota** [comment]
@groovemen About the size of the fields do not meet the BS4 the grid classes?

**Comment by groovemen** [comment]
Hello @iagofrota, do you mean the width of the field? Because it meets the grid system of Bootstrap.

**Comment by iagofrota** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/4643321/60370641-86c65100-99cd-11e9-9da8-b2565599b42d.png)
![SharedScreenshot2](https://user-images.githubusercontent.com/4643321/60370642-86c65100-99cd-11e9-902a-3a86aa318291.png)

@groovemen Even though I put the grid classes, the select field does not obey

**Comment by groovemen** [comment]
@iagofrota can you give us a link to your project? Or please try to set a width of 100%; for the input.

**Comment by iagofrota** [comment]
I made the change in the _plugin-bootstrap-select.scss file

```css
.bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {
  width: 200px;
}
```
to

```css
.bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {
  width: 100%;
}
```

and it worked!!
