### ISSUE TITLE
Header gets stretched when crawled

### ISSUE THREAD

**Issue by FabianKoestring** [creativetimofficial/ct-material-kit-pro#146]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When the page is crawled by google bot etc. the page should look similar to browser behavior.

# Current Behavior

The page looks different. The header get stretched.
![screenshot](https://user-images.githubusercontent.com/1252701/55325839-77933e00-5486-11e9-8499-c75fd2f0803c.jpg)

**Comment by groovemen** [comment]
Hello @FabianKoestring,

Thank you for using our products, I will ask you to give us more details about your issue (the exactly rezolution that triggers this issue)
Waiting for your answer.

All the best, 
Stefan
