### ISSUE TITLE
Discussion forum or howto for material-kit-pro ?

### ISSUE THREAD

**Issue by terchris** [creativetimofficial/ct-material-kit-pro#152]
Hi
This is not an issue. It is more a question on how to use the product. Is there a user forum to ask questions?
Where can I post a question like: 

Setting  css for  the background color on the pageHeader?
I'm trying to set the background color of a header so that depending on what is displayed I can change the background color.

Material Kit has defined pageHeader like this
pageHeader: {
//lots of settings
    alignItems: "center",
    "&:before": {
      background: "rgba(" + hexToRgb(blackColor) + ", 0.5)"
    },
    "&:before,&:after": {
      position: "absolute",
//more settings  
}

In my code I set the background color by 
    const XbackgroundColor= {
        height: "80vh",
        background: "#DD1367"
    };

And then use it like this:
className={classes.pageHeader} style={XbackgroundColor}>

The result is that the background color is set. But since the     
"&:before": {    background: 
is set it is a greyish color and not the pure "#DD1367" color.

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @terchris, 

Thank you for using our products, if you don't want the property set on :before on your project, you can simply erase it or overwrite it. Also, you can check our contact page: https://www.creative-tim.com/contact-us if you have other questions. 

All the best, 
Stefan
