### ISSUE TITLE
Bootstrap4 navbar-expand behaviour only works with lg breakpoint

### ISSUE THREAD

**Issue by timmygee** [creativetimofficial/ct-material-kit-pro#153]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Navbar toggle should appear for breakpoints below "lg"

# Current Behavior

Only if you use navbar-expand-lg will the toggle button appear at collapsed breakpoints

# Failure Information (for bugs)

No error output

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

In any of your navbar examples in the documentation [here](https://demos.creative-tim.com/material-kit-pro/docs/2.1/components/navbar.html):

1. Replace the navbar-expand-lg with something like navbar-expand-sm
2. Reduce viewport width
3. Observe toggle button disappearance

## Context

Bootstrap4 Material Kit Pro

* Device: Macbook Pro
* Operating System: MacOS Mojave
* Browser and Version: Chrome 75

## Failure Logs

N/A

**Comment by timmygee** [comment]
Not sure why this was closed without comment, but for reference to the rest of the community I've been advised that a workaround is to:

> change the @media-query for the .navbar-toggler

ie disable the `display: none` rule inside

```css
@media (min-width: 576px) {
    .navbar-expand-sm .navbar-toggler {
        ...
    }
}
```

**Comment by groovemen** [comment]
I would have left a comment here too, but thank you for being faster. 
Cheers, 
Stefan
