### ISSUE TITLE
hide mobile menu after click on menu

### ISSUE THREAD

**Issue by Jeraisy** [creativetimofficial/ct-material-kit-pro#155]
In mobile view, it doesn't collapse (hide) after menu item click.

Menu is covering the page.

Please share solution

**Comment by groovemen** [comment]
Hello @Jeraisy,

Thank you for using our products, please share with us your order ID to make a few verifications.

Best, 
Stefan

**Comment by Jeraisy** [comment]
Hi @groovemen, #100834926

**Comment by groovemen** [comment]
Hello again, 

I double-checked this issue on the live preview and also on the downloadable archive and it works just fine if you click on the icon and even on bodyClick. I will ask you to share with us a link to your project to be easier for us to find a solution. 

All the best, 
Stefan

**Comment by Jeraisy** [comment]
Hi Stefan,
I followed the same issue >  https://github.com/creativetimofficial/ct-material-kit-pro/issues/2

I working on one-page website. Mobile navigation stays over the page content after selecting a link on it.

I add data-toggle="collapse" and data-target=".in" to the <li> tags 
but it's not working.

**Comment by Lunum** [comment]
I'm also having this issue. I've tried just about everything to fix this solution including @Jeraisy 's issue. I'm trying to build out an SPA and am getting ready to strip out the entire navbar JS and CSS to go back to Bootstrap's default collapse nav.

**Comment by groovemen** [comment]
Hello @Lunum,

Thank you for using our products, if you want to use the default Bootstrap collapse, please follow the steps from this link: https://github.com/creativetimofficial/ct-material-kit-pro/issues/125. 

Also, I will ask you to share with us a video for your project. 

Best, 
Stefan
