### ISSUE TITLE
dropdown-item not functioning as expected on iOS Safari

### ISSUE THREAD

**Issue by mdublin** [creativetimofficial/ct-material-kit-pro#156]
- [x] I am running the latest version --> **YES**
- [x] I checked the documentation and found no answer --> **YES**
- [x] I checked to make sure that this issue has not already been filed --> **YES**
- [x] I'm reporting the issue to the correct repository (for multi-repository projects) --> **YES**

# Expected Behavior

Please describe the behavior you are expecting: 

In the context of a long dropdown menu with its height constrained using either Bootstrap's `pre-scrollable` class OR adding styling to the `dropdown-menu` <div> such as: 

```
 {
    height: auto;
    max-height: 200px;
    overflow-x: hidden;
}
```

I am expecting elements with the `dropdown-item` class to not disappear/appear inconsistently as I scroll up and down the dropdown menu on iOS Safari and I am expecting a scrollbar to appear as I scroll up and down the dropdown menu. 

# Current Behavior

What is the current behavior?

The current behavior: as I scroll up and down a dropdown menu with constrained height, elements/items in the dropdown menu with the `dropdown-item `class are disappearing/appearing inconsistently as I scroll up and down the dropdown menu. Additionally, no scrollbar appears when I swipe/scroll up and down on the dropdown menu. 

# Failure Information (for bugs)

no failure information. 

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Implement a dropdown menu thusly: 

```
<div class="dropdown">                                                                                                                            
             <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expande  d="false">                                                                                                                                                        Dropdown button                                                                                                                                         
             </button>                                                                                                                                       
            <div class="dropdown-menu pre-scrollable" aria-labelledby="dropdownMenuButton">                                                                  
             <a class="dropdown-item" href="#">Foo</a>                                                                                                    
             <a class="dropdown-item" href="#">Thing</a>                                                                                                                   
             <a class="dropdown-item" href="#">Something</a>                                                                                                    
             <a class="dropdown-item" href="#">Dudes</a>                                                                                                    
             <a class="dropdown-item" href="#">Birds</a>                                                                                                     
             <a class="dropdown-item" href="#">Nikes</a>                                                                                                     
             <a class="dropdown-item" href="#">Marsh mellows</a>                                                                                                    
             <a class="dropdown-item" href="#">Apples</a>                                                                                            
             <a class="dropdown-item" href="#">Dingles</a>                                                                                       
             <a class="dropdown-item" href="#">Berries</a>                                                                                                    
             <a class="dropdown-item" href="#">What not</a>                                                                                            
             <a class="dropdown-item" href="#">Something else here</a>                                                                                       
             <a class="dropdown-item" href="#">Action</a>                                                                                                    
             <a class="dropdown-item" href="#">Another action</a>                                                                                            
             <a class="dropdown-item" href="#">Something else here</a>                                                                                                                                                                        
           </div>                                                                                                                                            
       </div>                       

```
2. Open the dropdown menu on iOS safari
3. Observe that items in the dropdown menu disappear/reappear inconsistently and that no scrollbar is visible. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: iPhone8, iPhone5, iPad
* Operating System: OS 13.1.1, iOS 12.3.1, iOS 10.3.3
* Browser and Version: Safari (see versions above)

## Failure Logs

No failure logs.

**Comment by groovemen** [comment]
Hello @mdublin, 

Thank you for using our products, we reproduced your issue and tested on Safari browser on responsive and everything looks good, even the scrollbar. Check this image:
<img width="415" alt="Screenshot 2019-10-17 at 14 31 26" src="https://user-images.githubusercontent.com/21063398/67005467-5543d380-f0eb-11e9-96e1-698f0a5a85a7.png">

We also tested on iPhone (on Safari) and everything looks good. Please provide a video or a link to your project to find a solution for this problem. 
Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by mdublin** [comment]
@groovemen Thank you for responding so quickly. We are definitely seeing this issue across multiple iOS devices with the dropdown menu code/implementation I included above. Here is a video of what we're typically seeing with this dropdown wherein, as the user scrolls up or down, the items in the dropdown are disappearing/reappearing (also, note that the scrollbar is not visible): 

https://vimeo.com/367062399

**Comment by groovemen** [comment]
Hello again, 

As I told you above, we have tested the same code and it works just fine so we'll ask you to upload your project on a server and share it with us to inspect directly into your project to find a solution. 

Best, 
Stefan

**Comment by mdublin** [comment]
@groovemen As per email correspondence, cannot readily share the current implementation for further review (although it's really nothing exotic), so closing for now.
