### ISSUE TITLE
padding

### ISSUE THREAD

**Issue by loraxio** [creativetimofficial/ct-material-kit-pro#160]
# Expected Behavior
I want to be able to use the padding and margin layout utilities (pl-50, etc)

# Current Behavior
adding padding and margin CSS utilities does not give inline padding

**Comment by groovemen** [comment]
Hello @loraxio,

Thank you for using our products, please check the Bootstrap Spacing Utilities: https://getbootstrap.com/docs/4.0/utilities/spacing/#how-it-works You can set for the "pl-" numbers from 0 to 5. 

Best, 
Stefan
