### ISSUE TITLE
inline css for background-image

### ISSUE THREAD

**Issue by Gompali** [creativetimofficial/ct-material-kit-pro#165]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

I'm trying to integrate the login page under example folder.
I was expecting webpack to link correctly the background-image url('../assets/img/bg7.jpg')

# Current Behavior

What is the current behavior?
instead I see a broken link

# Failure Information (for bugs)
![image](https://user-images.githubusercontent.com/52416969/74980498-de1fa280-5430-11ea-8cc5-00e81ddfba79.png)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

Webpack seems to setup the correct url when the image is imported in a .css file, but it fails with inline-css.

Please can you tell me how to correct and in which css file ?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @Gompali,

Thank you for using our products, please set the right path to the image when you are using it in the CSS file.

Best, 
Stefan
