### ISSUE TITLE
Uncaught TypeError for SelectPicker in console

### ISSUE THREAD

**Issue by leijae** [creativetimofficial/ct-material-kit-pro#166]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Expected Behavior

Material Kit Pro bootstrap select picker; dropdown select list should be styled as mentioned here in documentation
![image](https://user-images.githubusercontent.com/50371033/75104298-3be8f180-55cd-11ea-9d95-599157a81a6f.png)

# Current Behavior

What is the current behavior?
Error in browser console
jquery.min.js:1251 Uncaught TypeError: $(...).selectpicker is not a function
    at HTMLDocument.<anonymous> (material-kit.js?v=2.0.6:276)
    at j (jquery.min.js:1197)
    at k (jquery.min.js:1203)
# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Using .net core 3.1 MVC, load scripts into layout partial
2. this line of code in the view                         @Html.DropDownListFor(m => m.BusinessType, Html.GetEnumSelectList<BusinessType>(), BusinessType.TaxExemptOrganization.ToString(), new { @class = "form-control selectpicker", data_style="btn btn-link" })
3. run in browsers and returns the following error

![image](https://user-images.githubusercontent.com/50371033/75104345-b6197600-55cd-11ea-82f4-5caaf7117d0f.png)

the following HTML is produced in the browser:
![image](https://user-images.githubusercontent.com/50371033/75104354-d6e1cb80-55cd-11ea-9760-258c9749a340.png)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: HP Spectre 360
* Operating System: Windows 10 Pro
* Browser and Version: Brave/Chrome newest version

**Comment by groovemen** [comment]
Hello @leijae,

Thank you for using our products, please try to reinitialize the .selectpicker after you populate it:
```
  // Activate bootstrap-select
  if ($(".selectpicker").length != 0) {
    $(".selectpicker").selectpicker();
  }
```
Hope that information helps you. Please let us know if we can help you with anything else.
All the best,
Stefan

**Comment by leijae** [comment]
Hi Stefan, 

Thanks for the tip, but unfortunately, it seems like initialization at the view doesn't fix the error:

![image](https://user-images.githubusercontent.com/50371033/75277862-7372bc00-57ce-11ea-9f15-19edf7d3f2d1.png)
 
The following is the code rendered:
![image](https://user-images.githubusercontent.com/50371033/75278030-c64c7380-57ce-11ea-9ea7-92880101a013.png)

And this is the UI:
![image](https://user-images.githubusercontent.com/50371033/75278083-dc5a3400-57ce-11ea-9f3b-073e754cf306.png)

**Comment by groovemen** [comment]
Then, it's probably from the scripts that you have loaded into your file project. Try to load **bootstrap-material-design** before the **bootstrap-select**.
<img width="1133" alt="Screenshot 2020-02-26 at 10 42 53" src="https://user-images.githubusercontent.com/21063398/75327274-c27b2880-5884-11ea-949d-952e7457f7b4.png">

**Comment by leijae** [comment]
oh my gosh, so silly... that's what it was. Thanks!
