### ISSUE TITLE
Profile Card Example does not work correctly

### ISSUE THREAD

**Issue by EcoFa** [creativetimofficial/ct-material-kit-pro#167]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

The Profile Card example from the documentation shows the same result when copying the code in the template project. In detail the Card Body should be showing under the card header image.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/55494034/76161790-e832e800-6136-11ea-8cc2-62ba3f99cb0d.png">

# Current Behavior

When I copy the code from the documentation in my project or in the template.html file of Material Kit Pro the card body and footer are hiding behind the image (Safari & Chrome testet on Mac).

<img width="577" alt="image" src="https://user-images.githubusercontent.com/55494034/76161827-51b2f680-6137-11ea-8031-8e816c6d57f6.png">

# Failure Information (for bugs)

I just copied the code to my project and expected to get the same result as shown in the documentation.
Do I need to add a min-Height for the header or something else?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Copy the code from the documentation in the template .html file

```
<div class="card card-profile ml-auto mr-auto" style="max-width: 360px">
  <div class="card-header card-header-image">
        <a href="#pablo">
            <img class="img" src="https://images.unsplash.com/photo-1492447273231-0f8fecec1e3a?auto=format&fit=crop&w=334&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D">
        </a>
    </div>

    <div class="card-body ">
        <h4 class="card-title">Alec Thompson</h4>
        <h6 class="card-category text-gray">CEO / Co-Founder</h6>
    </div>
    <div class="card-footer justify-content-center">
        <a href="#pablo" class="btn btn-just-icon btn-twitter btn-round">
            <i class="fa fa-twitter"></i>
        </a>
        <a href="#pablo" class="btn btn-just-icon btn-facebook btn-round">
            <i class="fa fa-facebook-square"></i>
        </a>
        <a href="#pablo" class="btn btn-just-icon btn-google btn-round">
            <i class="fa fa-google"></i>
        </a>
    </div>
</div>
```

2. Open the template File in a browser (Safari and Chrome on MAC)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: MacBook Pro
* Operating System: Catalina
* Browser and Version: Safari & Chrome (Latest Version)

**Comment by groovemen** [comment]
Hello @EcoFa,

Thank you for using our products, the card profile that you are using has a max-height property for the `.card-header-image` class: 
```
@media screen and (min-width: 767px)
.card-profile .card-header-image {
    max-height: 215px;
}
```
You can erase this property from **assets/scss/material-kit/_responsive.scss** at line 365. After you will recompile the SCSS your card will look like this:

<img width="497" alt="Screenshot 2020-03-09 at 10 44 23" src="https://user-images.githubusercontent.com/21063398/76196476-f8100200-61f2-11ea-9e40-d61765b3fd0d.png">

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by EcoFa** [comment]
Hello @groovemen,

Many thanks for the quick response. I have removed the max-height property and now the card works as desired.
Issue is closed. Thanks for the great product and the fast help.
