### ISSUE TITLE
[Bug] Incorrect navbar link colors when scroll/toggling transparency

### ISSUE THREAD

**Issue by kris-guy** [creativetimofficial/ct-material-kit-pro#182]
### Version
2.2.0
### Reproduction link
https://demos.creative-tim.com/marketplace/material-kit-pro/index.html
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome 99.0.4844.82
### Steps to reproduce
1. Open https://demos.creative-tim.com/marketplace/material-kit-pro/index.html
2. Scroll down until top navigation transitions (i.e. the "navbar-transparent" class is removed from <nav>)
3. Scroll back up to top of page
### What is expected?
When scrolling down, and navbar class "navbar-transparent" is toggled OFF, the navbar link color should be GREY.

When scrolling back up, and navbar class "navbar-transparent" is toggled ON, the navbar link color should be WHITE.
### What is actually happening?
When scrolling down, and navbar class "navbar-transparent" is toggled OFF, the navbar link color should be WHITE.

When scrolling back up, and navbar class "navbar-transparent" is toggled ON, the navbar link color should be GREY.

---
### Additional comments
1. When page loads - navigation looks like this: ![](https://i.ibb.co/rtgFDtR/image.png) - [Full Size](https://ibb.co/cvPk4vS)
2. The computed CSS color of the navbar-brand element is #fff / rgb(255,255,255) - shown here:
![](https://i.ibb.co/bz9F2C4/image.png) - [Full Size](https://ibb.co/PwHM9P2)

At this point everything is correct

4. Scroll down until the nav transitions from transparent to white.
5. The navigation now looks like this - the "navbar-brand" <a> text color is white:
![](https://i.ibb.co/Sr95JQ4/image.png) - [Full Size](https://ibb.co/gVBm6vL)
7. The computed CSS color is still #fff / rgb(255,255,255, even though the "navbar-transparent" style specifying that color is removed - see:
![](https://i.ibb.co/Y8BkQ88/image.png) - [Full Size](https://ibb.co/ftdpFtt)

Reverse issue

9. Scroll back to the top until nav transitions back to transparent
10. The navigation now looks like this - the "navbar-brand" <a> text color is grey :
![](https://i.ibb.co/JRszTn9/image.png) - [Full Size](https://ibb.co/BVCgJL9)
11. The computed CSS color is still #555 / rgb(85,85,85), even though the "navbar-transparent" style specifying the color as #fff / rgb(255,255,255 is present - see:
![](https://i.ibb.co/m0Q4V6C/image.png) - [Full Size](https://ibb.co/QksM3rF)

Refreshing / reloading the page resets the colors to "correct", but scrolling again causes the issue to reoccur.

**Comment by groovemen** [comment]
Hello @kris-guy, 

Thank you for using our products and for letting us know about this issue. We will write down for the next product update your solution.
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by groovemen** [comment]
Hello again, 

We have updated the product and solved this issue. Thank you for understanding. 

All the best, 
Stefan
