### ISSUE TITLE
Modal Backdrop

### ISSUE THREAD

**Issue by kolman1986** [creativetimofficial/ct-material-kit-pro#185]
When i use sign Up modal form the screen is dim and modal is showing,but i cant click on form or another element
Browser:Chromium
IDE:VS 2019

**Comment by groovemen** [comment]
Hello @kolman1986,

Thank you for using our products and for letting us know about this issue. We will update the inputs on the next product update. Until then we'll ask you to update the modal's inputs that you want to use with this one: https://www.creative-tim.com/learning-lab/bootstrap/forms/material-kit#form-styles 
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
