### ISSUE TITLE
Cannot click on Mobile menu when navbar has .container-fluid stead of .container

### ISSUE THREAD

**Issue by moohooooo** [creativetimofficial/ct-material-kit-pro#19]
I found that CSS has only .container

.nav-open nav .container {
    left: 0;
    -webkit-transform: translate3d(-245px, 0, 0);
    -moz-transform: translate3d(-245px, 0, 0);
    -o-transform: translate3d(-245px, 0, 0);
    -ms-transform: translate3d(-245px, 0, 0);
    transform: translate3d(-245px, 0, 0); }

**Comment by alexandru-paduraru** [comment]
@moohooooo please go to line 8373 where is the class `nav .container` and add `nav .container, nav .container-fluid` and then on line 8386 where is the class `.nav-open nav .container` and add the `.nav-open nav .container, .nav-open nav .container-fluid` and then it will work fine.

Best,
Alex
