### ISSUE TITLE
Navbar covers content on mobile

### ISSUE THREAD

**Issue by JonasEriksson** [creativetimofficial/ct-material-kit-pro#2]
Currently the mobile navigation stays over the page content after selecting a link on it. The user needs to press another time to close the mobile menu, this is not very intuitive. Can you fix this in the code base please?

**Comment by elvnthaus** [comment]
I ran into the same issue. I'm sure @JonasEriksson you figured it out but in case someone else runs into this and needs a fix:

Add `data-toggle="collapse"` and `data-target=".in"` to the `<li>` tags.

Consider adding it to the documentation? Its on bootstrap documentation but took me a while to find as I'm new.

**Comment by alexandru-paduraru** [comment]
@elvnthaus thank you for the suggestion. Sincerely, we didn't know that they have that option and we implemented a manual method which is closing the mobile navigation, then is scrolling to the element on another UI Kit that we have -> https://github.com/creativetimofficial/paper-kit/issues/8

We will add this update in v1.1.0 which will be released today.

Best,
Alex
