### ISSUE TITLE
Navbar hamburger does not show up on iPad (width 768px)

### ISSUE THREAD

**Issue by RedDuckss** [creativetimofficial/ct-material-kit-pro#25]
Title basically says it all. Was testing my site compatibility on several devices, and found that the navigation bar does not display correctly on an iPad Mini (width of 768 pixels). The navbar links are gone, indicating that it is not in the "collapsed" state, but the hamburger does not appear.

Notice how in this example image, the navbar (the blue bar at the very top) has no links (there are links, but it is in the "collapsed" state and thus they do not show) but the hamburger to open the menu does not show.

![No hamburger](http://i.imgur.com/sBzSfOd.png)

**Comment by alexandru-paduraru** [comment]
@RedDuckss thank you for pointing out. It seems that error appeared first time in the v1.1.0 update and we prepared a patch for it. Please check it here: https://github.com/creativetimofficial/material-kit-pro/issues/16 

Everything will work fine after that. We will fix this in the next v1.2.0 update.

Best,
Alex
