### ISSUE TITLE
Mobile menu not opening

### ISSUE THREAD

**Issue by gchamoun** [creativetimofficial/ct-material-kit-pro#26]
My mobile menu is not opening up when clicked on. 

![screen shot 2017-07-06 at 11 31 30 am](https://user-images.githubusercontent.com/26100049/27921884-d1c67856-623e-11e7-85c6-3d5fb59f6633.png)

**Comment by alexandru-paduraru** [comment]
@gchamoun thank you for using our product. It seems you have some Javascript Errors in the console. Please make sure you don't have any errors then let us know if the menu is still not working. If you can send a link to your website we would be glad to check it.

Best,
Alex
