### ISSUE TITLE
Register / Sign Up Modal doesnt respond

### ISSUE THREAD

**Issue by sebclark** [creativetimofficial/ct-material-kit-pro#27]
http://demos.creative-tim.com/material-kit-pro/index.html

click the Javascript components -> Sign Up

The Register modal doesnt resize/respond. It works fine as stand alone here: examples/signup-page.html

**Comment by dragosct10** [comment]
Hi @sebclark! Sorry for the late response. For fixing the issue with the Modal on responsive please take the uploaded scss partial `_dialogs.scss` and go in your project `assets/sass/material-kit/_dialogs.scss` and replace with the new one. After you do that please compile your scss with [Koala](koala-app.com) and be sure that your output path is `assets/css/material-kit.css`. Please let us know if everything is working fine!

[_dialogs.scss.zip](https://github.com/creativetimofficial/material-kit-pro/files/1152053/_dialogs.scss.zip)

Regards,
Dragos
