### ISSUE TITLE
Rotating Cards 'back back-background' not loaded for new items when scroll 

### ISSUE THREAD

**Issue by MostafaAttia** [creativetimofficial/ct-material-kit-pro#29]
I have a problem with rotating cards when used with (masonry + infinitescroll + imagesLoaded), the NEWLY loaded items has the image for the 'front' only, the div with class 'back back-background' is just a gray background, the image is not loaded (however, it loaded if resizing the browser window) :

![back](https://user-images.githubusercontent.com/12887130/28361919-19fb2f1a-6c83-11e7-9e6c-78d265941e9f.png)

![screenshot from 2017-07-19 13-09-02](https://user-images.githubusercontent.com/12887130/28362015-7ef8657c-6c83-11e7-8e84-283214e17284.png)

**Comment by dragosct10** [comment]
Hi @MostafaAttia! For fixing this issue you must make some modifications. You need to go in `assets/js/material-kit.js` and at the bottom of the page and add the following function:

```js
function RotateCardReset(){
     setTimeout(function(){
        $('.card-rotate:not(.card-checked) .card-image > .back').each(function(){
            var card_image_height = $(this).parent().height();
            var card_image_width = $(this).parent().width();

            $(this).css({
                'height': card_image_height + 'px',
                'width': card_image_width + 'px'
            });

            $(this).parent().parent().parent().addClass('card-checked');

            if($(this).hasClass('back-background')){
                var img_src = $(this).siblings('.front').find('img').attr('src');
                $(this).css('background-image','url("' + img_src + '")');
            }
        });
    },1000);
 }
```

Now you have to call this function like this:

```js
$(document).ready(function(){
    RotateCardReset();
});
```
Please let us know if everything is working fine!

Regards,
Dragos

**Comment by MostafaAttia** [comment]
Thanks @dragosct10 ,  Now its working when calling `RotateCardReset()` inside `imagesLoaded()` like this:

`// Trigger Masonry as a callback 

         function( newElements ) {
                // hide new items while they are loading
                var $newElems = $( newElements ).hide();
                $('#loading-spin').show();
                // ensure that images load before adding to masonry layout
                $newElems.imagesLoaded(function(){
                    $('#loading-spin').hide();
                    // show elems now they're ready
                    RotateCardReset();  // Reset Rotating Cards
                    $newElems.show();
                    $container.masonry( 'appended', $newElems, true );
                });
            });
`

**Comment by MostafaAttia** [comment]
@dragosct10  After testing a few times, I found that the card layout is broken with some images, But after I modified your function to delete your resetting of Width and Height, Everything works fine now.
So I deleted these lines from your `RotateCardReset()` 
`
var card_image_height = $(this).parent().height();
            var card_image_width = $(this).parent().width();
            $(this).css({
                'height': card_image_height + 'px',
                'width': card_image_width + 'px'
            });
`
