### ISSUE TITLE
Template not displaying correctly (Developing with Laravel)

### ISSUE THREAD

**Issue by moharrum** [creativetimofficial/ct-material-kit-pro#35]
Hi,

I'm using Laravel to build my app, after buying this template here is what I did:

1. Copied _**assets**_ to **_public/plugins/material-kit_**
2. Opened my login page and pasted your code.
3. Update the links on the page to include styles and scripts using Blade.
4. All style and script files are loaded successfully but the page is messed up.
5. No console errors are reported or 404 errors regarding styles, scripts or imgs.

Here is how the page looks like now: http://imgur.com/a/WTMhH

**Comment by alexandru-paduraru** [comment]
@moharrum thank you for using our product and sorry for the late response. It seems you are missing one CSS file, can you please send us a link to your webapp so we can check?

Best,
Alex

**Comment by moharrum** [comment]
Hello @alexandru-paduraru and sorry for the delay. This is the [app link](http://45.33.78.212/) .

Thanks

**Comment by alexandru-paduraru** [comment]
@moharrum very weird, I've never seen that before. It seems some CSS is missing, here is the style on our presentation page:

<img width="1440" alt="screen shot 2017-08-28 at 16 03 20" src="https://user-images.githubusercontent.com/2517758/29774585-a242fadc-8c0a-11e7-84d9-448e75885a14.png">

Here is the style on your page, you see the missing CSS properties:

<img width="1440" alt="screen shot 2017-08-28 at 16 03 43" src="https://user-images.githubusercontent.com/2517758/29774599-acdae0ae-8c0a-11e7-935c-dc057c5aac4e.png">

Is something that is interfering with the CSS? Can you please add the not minified version of the file and let us know after you did that?

Best,
Alex

**Comment by moharrum** [comment]
Hello dear @alexandru-paduraru , this is the not minified file : [material-kit.zip](https://github.com/creativetimofficial/material-kit-pro/files/1261897/material-kit.zip)

I found the problem though, comparing the css file downloaded from the dashboard and the one in the demo, they are not the same, downloaded one looks incomplete.

Here is an image of the downloaded file from my account dashboard: [Uploading Screenshot from 2017-08-30 01-14-02.png…]() , and this one from the demo:  [Uploading Screenshot from 2017-08-30 01-14-13.png…]() .

Anyway, I copied the css file contents from the demo and it worked.

**Comment by Bagmaz** [comment]
Hi, what is your laravel version?
You must locate file like this ...

This is for sass file

<img width="348" alt="screen shot 2017-08-31 at 11 44 55 am" src="https://user-images.githubusercontent.com/20259560/29917326-ecad70d2-8e41-11e7-916a-0bf858011400.png">

and you must change resources/assets/sass/app.scss to this

`// Fonts
@import url("https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons");
@import "~font-awesome/scss/font-awesome";

// Variables
//@import "variables";

// Bootstrap
@import "~bootstrap-sass/assets/stylesheets/bootstrap";

@import "../mk-pro/assets/sass/material-kit";
`

**Comment by alexandru-paduraru** [comment]
@moharrum I understand. Can you please use the material-kit.css which looks like this:

<img width="845" alt="screen shot 2017-09-04 at 13 08 25" src="https://user-images.githubusercontent.com/2517758/30022032-29e8626c-9172-11e7-8323-bedea526865a.png">

It seems the material-kit.min.css is having some issues, we will check again and fix that.

Best,
Alex

**Comment by moharrum** [comment]
@Bagmaz , I'm using L5.4. But I'm not compiling any scss files my friend and not planning to do so, I'm using the precompiled min.css file.

@alexandru-paduraru , yup material-kit.css is doing the magic :).
