### ISSUE TITLE
hamburger kicks in one pixel early...

### ISSUE THREAD

**Issue by ConfusedVorlon** [creativetimofficial/ct-material-kit-pro#42]
I have an observation here.

with regard to the hamburger and other responsive utilities

In bootstrap - 768 (or larger) is treated as the tablet size
767 or lower is phone

see [bootstrap responsive utilities](https://getbootstrap.com/docs/3.3/css/#responsive-utilities
)

this means that an iPad is tablet for portrait and landscape

in materialkit, 768 is considered mobile
this means that

1. an iPad can be both mobile and non-mobile (depending on orientation)
2. there are odd inconsistencies when you try to run things using the bootstrap breakpoints

**Comment by ConfusedVorlon** [comment]
note - this is only recently true; Until [issue#16](https://github.com/creativetimofficial/material-kit-pro/issues/16) the hamburger did not show at size 768

this means that there are probably not lots of sites optimised around the existing assumptions

**Comment by dragosct10** [comment]
Hi, @ConfusedVorlon! Sorry for the late response. In the next update which will be very soon because we will update the product to Bootstrap 4 Beta, we will initialize the responsive menu at 991px like it is normal.

Regards,
Dragos

**Comment by ConfusedVorlon** [comment]
eek - whilst I'm excited that you're updating to bootstrap 4, will you be maintaining a branch on bootstrap 3?

I suspect it will be a big job to update my whole site to bootstrap 4 and it would be nice to have a bootstrap 3 option available until that can happen.

**Comment by dragosct10** [comment]
Hi, @ConfusedVorlon! Yes, the old Material Kit Pro on Bootstrap 3 will remain on another branch and the problem will be fixed also on Bootstrap 3. 

Regards,
Dragos

**Comment by erikjara** [comment]
@dragosct10 some ETA for Bootstrap 4? I want to design in Material Kit Pro, but I need flex and some features of BS4.

Thanks :)

**Comment by dragosct10** [comment]
Hi, @erikjara! We still working on the version of the Material Kit Pro on BS4, in 1-2 weeks I think we will release the update. There are a lot of new things that are changed in the new version of BS4 and we want to work carefully with every detail to have in the final a good version of the product.

Regards,
Dragos
