### ISSUE TITLE
Refresh page on navbar-fixed-top navbar-color-on-scroll

### ISSUE THREAD

**Issue by Bagmaz** [creativetimofficial/ct-material-kit-pro#43]
On page refresh or redirect to another page with id on middle of screen the navbar still transparent.

<img width="1242" alt="screen shot 2017-11-10 at 6 30 02 pm" src="https://user-images.githubusercontent.com/20259560/32670807-3b50ed8c-c645-11e7-92f4-0bcb80949c64.png">

**Comment by dragosct10** [comment]
Hi, @Bagmaz! We tried to refresh the page and for us everything working fine.

Regards,
Dragos

**Comment by Bagmaz** [comment]
Hi, @dragosct10 
I think this problem solved in version 1.2.1

Thank you.

**Comment by Bagmaz** [comment]
@dragosct10 
Actually this problem from this link, please check this link
[http://demos.creative-tim.com/material-kit-pro/examples/ecommerce.html](url)

**Comment by zitengine** [comment]
I am facing this problem too, its not for link, its may be for java script
please solve this soon
navbar-color-on-scroll issue

**Comment by dragosct10** [comment]
Hi! To fix the problem please take the uploaded javascript file and go in `assets/js/material-kit.js` and replace with the uploaded file. After that everything will work fine! 

[material-kit.js.zip](https://github.com/creativetimofficial/material-kit-pro/files/1591100/material-kit.js.zip)

Regards,
Dragos
