### ISSUE TITLE
Inputs with a placeholder should never have the is-empty class applied

### ISSUE THREAD

**Issue by ziemkowski** [creativetimofficial/ct-material-kit-pro#48]
When an input has no value but contains a placeholder, floating labels don't float on init and input blur, drawing over the placeholder:
![image](https://user-images.githubusercontent.com/704098/33716713-31fca416-db25-11e7-898c-7cc2ae8dbdae.png)

When it should always look like this:
![image](https://user-images.githubusercontent.com/704098/33716667-08596f54-db25-11e7-8a59-8b145facfe46.png)

Example HTML:
```html
<div class="form-group label-floating">
  <label class="control-label">Phone Number</label>
  <input type="email" class="form-control" placeholder="(123) 456-7890">
</div>
```

This issue also applies to `<select>` elements where the selected option's value is empty but the option text is not, suggesting jQuery's `val()` is being used to determine if there is content in the input area.

For anybody using ES6 and encountering this issue, this snippet works around the issue for inputs _but not select's with empty values:_
```js
$.material.init()

const placeholderSelector = '.form-group.is-empty input[placeholder]:not([placeholder=""])'
const removeEmpty = (input) => {
  $(input).closest('.form-group.is-empty').removeClass('is-empty')
}

$(placeholderSelector).each((i, input) => removeEmpty(input))
$('body').on('blur', placeholderSelector, (e) => removeEmpty(e.currentTarget))
```

**Comment by alexandru-paduraru** [comment]
@ziemkowski thank you for the example and the fixing snippet. We will fix this in a next release and it will also be fixed when we release the Bootstrap 4 version (it should come this week) :D
