### ISSUE TITLE
Sidebar collapse default by bootstrap

### ISSUE THREAD

**Issue by dragosct10** [creativetimofficial/ct-material-kit-pro#49]
Hi! If you want to have the default collapse of the navbar, please follow the next steps: 

1. You must put on the `body` tag the class `.bootstrap-collapse` ( in case that you want to return to our collapse style please put the class on the `body` tag `.material-collapse`).

2. Go in the html pages and add to the `button` from the `nav` tag the attribute `data-target="#menu"` like in the example below:

```html
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
</button>
```
3. After that you must go below to the div with class `.navbar-collapse` and add the `id` on this div with the same value from the attribute `data-target=" "`, in our case the value `menu`: 

```html
<div class="collapse navbar-collapse" id="menu">
          //content
</div>
```

4. Now you have to go in `assets/sass/material-kit/_responsive.scss` and `assets/sass/material-kit/_dropdown.scss` and replace them with the scss partials that I uploaded here.

[_dropdown.scss.zip](https://github.com/creativetimofficial/material-kit-pro/files/1559661/_dropdown.scss.zip)
[_responsive.scss.zip](https://github.com/creativetimofficial/material-kit-pro/files/1559663/_responsive.scss.zip)

5. Please compile your scss with [Koala](koala-app.com) and be sure that your output path is `assets/css/material-kit.css`

Regards,
Dragos

**Comment by eleventhaus** [comment]
Does this also work for the latest update using bootstrap4?

**Comment by dragosct10** [comment]
Hi, @eleventhaus! Yes, the collapse sidebar option must work also on bootstrap 4. 

Regards, 
Dragos

**Comment by Wegazz** [comment]
Dear friend, links to the files you uploaded. No longer active :( 
'_dropdown.scss.zip and _responsive.scss.zip'

**Comment by dragosct10** [comment]
Hi, @Wegazz! Thank you for using our products. Please see this issue in order to make this work #125. 

Regards, 
Dragos
