### ISSUE TITLE
Failing to import SCSS

### ISSUE THREAD

**Issue by raphaelarias** [creativetimofficial/ct-material-kit-pro#53]
Hi, would you know why the SCSS importing is not working?

While processing files
   /src/client/scss/material-kit.scss: Scss compiler error: no mixin named hover
   
   Backtrace:
   core-bootstrap/scss/reboot:196

We've tried everything, but we can't manage to get it working.

**Comment by dragosct10** [comment]
Hi, @raphaelarias! Thank you for using our product. Please, can you tell if you include in your scss the mixin named hover because the error seems to refer to this? 

Regards,
Dragos

**Comment by michelson** [comment]
ref https://github.com/creativetimofficial/material-kit/issues/106

**Comment by raphaelarias** [comment]
Yes. We include everything. Usually we don't have problems to make SCSS work, but this one we couldn't manage to fix. So for now we are just using the CSS.

I'll send a screenshot.

**Comment by dragosct10** [comment]
Hi, @raphaelarias! Please, take the latest version `2.0.3` of the product and try to see if it works now. Regards, Dragos

**Comment by raphaelarias** [comment]
Thanks!! I'll give it try.

**Comment by JKE-be** [comment]
Hi @dragosct10,

Nice job!

Do you have an ETA for 2.0.3 lite version?
There are always many bugs in saas compilation making it not customizable.

> core/mixins/_utilities.scss:53: Mixins may not be defined within control directives or other mixins. (Sass::SyntaxError)
> 
> core/mixins/_utilities.scss:66: Mixins may not be defined within control directives or other mixins. (Sass::SyntaxError)
> 
> core/mixins/_buttons.scss:30: Invalid CSS after "...or($background)": expected "}", was "&:hover," (Sass::SyntaxError)
> 
> core/mixins/_forms.scss:154:in `bmd-form-color': Base-level rules cannot contain the parent-selector-referencing character '&'. (Sass::SyntaxError)
> 
> core/mixins/_forms.scss:278:in `bmd-form-size-variant': Base-level rules cannot contain the parent-selector-referencing character '&'. (Sass::SyntaxError)
> 
> core/mixins/_drawer.scss:5:in `bmd-drawer-x-out': Base-level rules cannot contain the parent-selector-referencing character '&'. (Sass::SyntaxError)

Thanks in advance

**Comment by dragosct10** [comment]
Hi, @JKE-be! Thank you for using our product. The version 2.0.3 is released and you can take it. We resolved these issues in the new version. Regards, Dragos

**Comment by dragosct10** [comment]
Hi! You are in the Material Kit PRO GitHub repo and you have the free version. For the free version it's not released yet the update. Regards, Dragos
