### ISSUE TITLE
Carousel not fully responsive (text overlaps with arrows)

### ISSUE THREAD

**Issue by asyi** [creativetimofficial/ct-material-kit-pro#55]
Hi, I'm trying to make use of the "Testimonials 2" Carousel provided in the Material-Kit-Pro sections template. However, I've discovered that it isn't properly responsive, because when the screen width gets smaller:

1) the text begins to overlap with the arrows.
2) the arrows shift vertically so that it's not in the same place on one slide as it is on the next. 
3) the dark background container changes sizes on each slide, depending on length of text. 

             <div class="testimonials-2 section-dark">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div id="carouselExampleIndicatorss" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="carousel-item">
                                        <div class="card card-testimonial card-plain">
                                            <div class="card-avatar">
                                                <a href="#pablo">
                                                    <img class="img" src="assets/img/faces/kendall.jpg">
                                                </a>
                                            </div>
                                            <div class="card-body">
                                                <h5 class="card-description">"I speak yell scream directly at the old guard on behalf of the future. I gotta say at that time I’d like to meet Kanye I speak yell scream directly at the old guard on behalf of the future. My brother Chance!!!
                                                    <br>Thank you for letting me work on this masterpiece. One of my favorite people."
                                                </h5>
                                                <h4 class="card-title">Kendall Thompson</h4>
                                                <h6 class="card-category text-muted">CEO @ Marketing Digital Ltd.</h6>
                                                <div class="footer">
                                                    <i class="material-icons text-warning">star</i>
                                                    <i class="material-icons text-warning">star</i>
                                                    <i class="material-icons text-warning">star</i>
                                                    <i class="material-icons text-warning">star</i>
                                                    <i class="material-icons text-warning">star</i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="carousel-item active">
                                        <div class="card card-testimonial card-plain">
                                            <div class="card-avatar">
                                                <a href="#pablo">
                                                    <img class="img" src="assets/img/faces/christian.jpg">
                                                </a>
                                            </div>
                                            <div class="card-body">
                                                <h5 class="card-description">"Thank you Anna for the invite thank you to the whole Vogue team Called I Miss the Old Kanye At the God's last game Chop up the soul Kanye. I promise I will never let the people down. I want a better life for all!!! Pablo Pablo Pablo Pablo! Thank you Anna for the invite thank you to the whole Vogue team."
                                                </h5>
                                                <h4 class="card-title">Christian Louboutin</h4>
                                                <h6 class="card-category text-muted">Designer @ Louboutin &amp; Co.</h6>
                                                <div class="footer">
                                                    <i class="material-icons text-warning">star</i>
                                                    <i class="material-icons text-warning">star</i>
                                                    <i class="material-icons text-warning">star</i>
                                                    <i class="material-icons text-warning">star</i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleIndicatorss" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleIndicatorss" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
If you could please provide a solution, it would be much appreciated!
![screen shot 2018-01-25 at 2 02 15 pm](https://user-images.githubusercontent.com/16291524/35408281-94f4d344-01dc-11e8-81db-04690b6cd086.png)
![screen shot 2018-01-25 at 2 02 37 pm](https://user-images.githubusercontent.com/16291524/35408282-94fe7f8e-01dc-11e8-9aff-f5d42a229169.png)

**Comment by dragosct10** [comment]
Hi, @asyi! Thank you for using our product. To fix these issues please take the uploaded scss partial and go to `assets/scss/_responsive.scss` and replace with the new one. 

Regards,
Dragos

[_responsive.scss.zip](https://github.com/creativetimofficial/material-kit-pro/files/1667104/_responsive.scss.zip)

**Comment by asyi** [comment]
Hi @dragosct10, thanks for getting back to me so quickly - but unfortunately the new _responsive.scss file doesn't seem to have any effect on the responsiveness of the carousel. The three issues remain. (See screen-recording)
[carousel-issues.zip](https://github.com/creativetimofficial/material-kit-pro/files/1668223/carousel-issues.zip)

**Comment by dragosct10** [comment]
Hi, @asyi! Sorry for the late response. You are sure that you compiled your scss with the steps that we showed in the [documentation](http://demos.creative-tim.com/material-kit-pro/docs/2.0/components/colors.html) because from your video it seems that nothing changed? 

Regards,
Dragos

**Comment by asyi** [comment]
@dragosct10 
Hi Dragos, no problem on the late reply! I tried to run gulp compile:scss as per instructed, but here's what I kept getting back: 

`[19:04:41] Using gulpfile ~/Documents/Hubba-Homepage/materialpro-hubba-homepage/gulpfile.js
[19:04:41] Task 'compile:scss' is not in your gulpfile
[19:04:41] Please check the documentation for proper gulpfile formatting`

I tried running gulp watch as well, but even if it gave me no errors, it seems like there was still no effect on the responsiveness of the carousel...

**Comment by dragosct10** [comment]
Hi, @asyi! I noticed that you put in your `gulp compile:scss` but this it is not the task name. The name of the task that you must put in the console is `gulp compile-scss` and yes you did well that you opened the watch to compile the scss. OK, I will send you a screenshot to see what properties to put for fixing this. It's weird that the scss partial it's not working for you because I verified the partial and the properties are there. Please see this images from below: 

<img width="1374" alt="screen shot 2018-01-31 at 10 07 59" src="https://user-images.githubusercontent.com/17456857/35611749-c491e948-066e-11e8-8f14-f0399f1cfa7b.png">

If you will notice there are 3 properties that are inserted for the carousel on card-body on max-width: 991. These 3 properties you must put to fix the issue. 

Regards, 
Dragos

**Comment by asyi** [comment]
Hi Dragos, 

I checked the docs and it looks like there's a typo on instruction #5 http://demos.creative-tim.com/material-kit-pro/docs/2.0/components/colors.html because it says  `gulp compile:scss` instead of `gulp compile-scss`.

Anyway, I did follow you new instructions and the file did compile properly so thank you for that! However, while the arrows no longer move up and down and the container size remains stable, the arrows still continue to overlap with the text...

![screen shot 2018-01-31 at 10 48 22 am](https://user-images.githubusercontent.com/16291524/35632437-aa83cd0e-0674-11e8-9538-e2ba54860365.png)

**Comment by dragosct10** [comment]
Hi, @asyi! You can adjust the value of `max-width` with what value do you want to not overlap the text. 

Regards,
Dragos
