### ISSUE TITLE
Missing docs for css utilities

### ISSUE THREAD

**Issue by labs20** [creativetimofficial/ct-material-kit-pro#57]
Hi, I've been complaining about that since my purchase, a year ago. I've updated to the lastest B4 version, and I'm still not able to find proper documentation about your css utilities class.

Take header-filter as an example (but do not limit to it). If I'm not aware of how much of those classes there are, nor how many variations or configurations they support, I'll end up recreating a bunch of css classes only to solve needs that are already solved in first place.

Please provide that.

**Comment by dragosct10** [comment]
Hi, @labs20! Thank you for using our product. Please, can you tell us about which classes do you want details? 

Regards,
Dragos

**Comment by labs20** [comment]
Hi! You're most welcome. It's a great product.

Well, thats exactly the point! I dont know which classes (utility classes) do exists to begin with. Left alone asking details about'em =]

What I'm asking is a section in your documentation alas "Utilities" section in Bootstrap docs, where you could tell me all about the small classes that may be around and I'm not aware of. Do I need to create a ".rounded" class to keep me from hurting on my DIVs edges or there are a pre-made one, ready for me to use it?

Thats it. =]

**Comment by dragosct10** [comment]
Hi, @labs20! Sorry for the late response. Thank you for your idea we will do an update soon and we will create a small section with that classes in the docs. 

Regards, 
Dragos
