### ISSUE TITLE
Error when I try to compile with gulp compile:scss

### ISSUE THREAD

**Issue by lumalisan** [creativetimofficial/ct-material-kit-pro#60]
Hello,

I purchased material kit pro recently and when trying to change the colors from the file _colors.scss and compile it with the command gulp compile:scss I get the following error:

C:\Users\Lisier\Downloads\BS4>gulp compile:scss
module.js:557
    throw err;
    ^

Error: Cannot find module 'gulp-open'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Lisier\Downloads\BS4\gulpfile.js:6:20)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

Also, when I try to do it using the gulp watch command, the same thing happens to me. I'm running this commands on the same folder where gulpfile.js and package.json are located.
Any solution?

**Comment by dragosct10** [comment]
Hi, @lumalisan! Thank you for using our product. You are sure that you followed all the steps that are mentioned there in docs? 

Regards, 
Dragos

**Comment by lumalisan** [comment]
Hello @dragosct10,

Thank you for answering so quickly. I have repeated the process with another new BS4 file but it has not let me compile it. Is there a problem if I change the colors using a custom.css file?

**Comment by dragosct10** [comment]
Hi, @lumalisan! Please add this line in your console: `npm install gulp-open --save-dev` . This will fix the problem and you will can compile with gulp.

Regards,
Dragos

**Comment by lumalisan** [comment]
Hello @dragosct10,

Yes! Now it works. But for some reason, when I try to change a color from the file _brand.scss and then I open any page, it does not change. 

![captura de pantalla 47](https://user-images.githubusercontent.com/36240281/35972959-f9777176-0cd3-11e8-9e17-a14e7feae338.png)
![captura de pantalla 48](https://user-images.githubusercontent.com/36240281/35972960-f998b62e-0cd3-11e8-8948-9efd325702c2.png)
![captura de pantalla 49](https://user-images.githubusercontent.com/36240281/35972961-f9b964a0-0cd3-11e8-8291-16880b534b33.png)

Am I doing something wrong?

**Comment by dragosct10** [comment]
Hi, @lumalisan! Please make sure that you make changes in the right file, because please look at my [video](https://www.dropbox.com/s/ylyve5vm42xyeou/mk-compile.mov?dl=0) and see that on our side everything is working fine. 

Regards, 
Dragos

**Comment by lumalisan** [comment]
Hello @dragosct10,

Thanks for the video and sorry for answering so late. I have followed all the steps of the video that you have passed me, I have done exactly the same in the directory where I have the package.json in my project and it does not let me change the colors. But it's ok, I will change it through CSS files.

Regards,
Lumalisan.

**Comment by dragosct10** [comment]
Hi, @lumalisan! It's weird because it's obviously that something is happened there. If you want you can try to compile the scss with [Koala](http://koala-app.com/). 

Regards, 
Dragos

**Comment by lumalisan** [comment]
Hello @dragosct10,

I tried to compile the scss with Koala but the program didn't find the scss files that I had to compile, I do not understand why this happens. In my proyect folder did not work and in a new folder with Material Kit files without modifying it did not work either. The folder on the right is a new file of BS4 Kit Material.

Best regards,
Lumalisan.

**Comment by dragosct10** [comment]
Hi @lumalisan! Regard to gulp did you tried to update your gulp and all the npm, because it's possible to be different versions? Regards, Dragos

**Comment by kawaijoe** [comment]
Hello @dragosct10 

Sorry for opening this issue again. However, I am currently encountering the exact same issue. (As the screenshot posted above) I ran npm install command to install the required packages stated in the package.json.

<img width="481" alt="screen shot 2018-03-14 at 10 20 18 pm" src="https://user-images.githubusercontent.com/7107487/37407914-ebc76ba4-27d5-11e8-906c-3af0dcd04e8d.png">

Any other ideas why this might happen? Thanks!

**Comment by kawaijoe** [comment]
@lumalisan Might be slightly late on this one. But you might want to try out what I mentioned on #78

**Comment by dragosct10** [comment]
Hi, @kawaijoe! Thank you for using our product. Did you try to see if it is the problem from #78? Regards, Dragos

**Comment by dragosct10** [comment]
Hi! I found the problem and please follow the next steps to fix the problem: 

1. Take the uploaded `gulpfile.js` and replace in the project.
[gulpfile.js.zip](https://github.com/creativetimofficial/material-kit-pro/files/1822578/gulpfile.js.zip)

2. Go in the project to `assets/scss/` and replace the name of the file `material-kit-pro.scss` in `material-kit.scss`. 

3. Now you can compile the scss with npm. 

Regards,
Dragos

**Comment by LambertStrategy** [comment]
I'm having the same problem compiling the scss with the steps in the documentation. 

`+ gulp-install@1.1.0
added 4 packages from 5 contributors in 2.928s
LSGmainframe:assets LambertStrategy$ npm list --depth=0
material-kit-pro@2.0.3 /Users/LambertStrategy/Sites/local-hubl-server/work/hubthemes/lambertstrategy/assets
├── gulp@3.9.1
├── gulp-autoprefixer@4.1.0
├── gulp-clean@0.3.2
├── gulp-install@1.1.0
├── gulp-open@2.1.0
├── gulp-sass@3.2.1
└── gulp-sourcemaps@2.6.4

LSGmainframe:assets LambertStrategy$ gulp compile-scss
[14:59:50] Using gulpfile ~/Sites/local-hubl-server/work/hubthemes/lambertstrategy/assets/gulpfile.js
[14:59:50] Starting 'compile-scss'...
[14:59:50] Finished 'compile-scss' after 10 ms
LSGmainframe:assets LambertStrategy$ gulp compile-scss
[15:04:19] Using gulpfile ~/Sites/local-hubl-server/work/hubthemes/lambertstrategy/assets/gulpfile.js
[15:04:19] Starting 'compile-scss'...
[15:04:19] Finished 'compile-scss' after 10 ms
LSGmainframe:assets LambertStrategy$ gulp open-app
[15:06:36] Using gulpfile ~/Sites/local-hubl-server/work/hubthemes/lambertstrategy/assets/gulpfile.js
[15:06:36] Starting 'open'...
[15:06:36] Finished 'open' after 4.16 ms
[15:06:36] Starting 'watch'...
[15:06:36] Finished 'watch' after 3.83 ms
[15:06:36] Starting 'open-app'...
[15:06:36] Finished 'open-app' after 22 μs
^C
LSGmainframe:assets LambertStrategy$ compile-scss
bash: compile-scss: command not found
LSGmainframe:assets LambertStrategy$ gulp compile-scss
[15:09:18] Using gulpfile ~/Sites/local-hubl-server/work/hubthemes/lambertstrategy/assets/gulpfile.js
[15:09:18] Starting 'compile-scss'...
[15:09:18] Finished 'compile-scss' after 9.64 ms
LSGmainframe:assets LambertStrategy$ `

**Comment by dragosct10** [comment]
Hi, @LambertStrategy! Thank you for using our product. Please take the latest version of the product and please tell us what happens with your scss? Regards, Dragos
