### ISSUE TITLE
BS4 SCSS compile error (Material Kit Pro 2.0.1)

### ISSUE THREAD

**Issue by JDesignEra** [creativetimofficial/ct-material-kit-pro#62]
When trying to compile material-kit pro.scss I am getting an error with both [Koala compiler](http://koala-app.com/) and CLI (sass) compiler.

`Error: Mixins may not be defined within control directives or other mixins.`
`on line 53 of assets/scss/core/mixins/_utilities.scss`

**Comment by dragosct10** [comment]
Hi, @JDesignEra! Please take the latest version `2.0.2` and try to compile the scss. 

Regards, 
Dragos

**Comment by michelson** [comment]
ref https://github.com/creativetimofficial/material-kit/issues/106

**Comment by pdeka** [comment]
Hi, The following construct is not legal in sass 
`@mixin create-colored-badges(){
    @mixin badges-color($color){`
Please look at material-kit-pro-html-v2.0.2/assets/scss/core/mixins/_utilities.scss

I am using Sass 3.5.5

Can you please fix this? It's really annoying (specifically when ones pays for it) as I cannot include the sass files as part of my project and continue to compile using gulp-sass and your build file.

**Comment by dragosct10** [comment]
Hi, @pdeka! Please, can you send us an email to our support address to send you the good scss folder, please? Regards, Dragos

**Comment by monaco-friends** [comment]
@dragosct10 we purchased the package but have the same issue.... Where can i download package 2.0.3? We only got the 2.0.2 which still has the errors

**Comment by dragosct10** [comment]
Hi, @monaco-friends! You can download the latest version from your account. Regards, Dragos

**Comment by dragosct10** [comment]
Hi, @mc100s! Thank you for using our product. There will be also an update to fix these issues. Regards, Dragos

**Comment by KLM-DS-GIT** [comment]
I too am having the problem - where can I get v. 2.0.3 for pro version? Thanks.

**Comment by AlekseyKorzun** [comment]
Same; opened a ticket

**Comment by dragosct10** [comment]
Hi, @KLM-DS-GIT! Thank you for using our product. You can take the latest version of the pro product from your account. Regards, Dragos

**Comment by dragosct10** [comment]
Hi, @AlekseyKorzun! Thank you for using our product. Do you have the PRO version? Regards, Dragos

**Comment by fbacker** [comment]
Any progress on this? Also using PRO. Downloaded it just now and it's version 2.0.2
material-kit-pro-html-v2.0.2

**Comment by fbacker** [comment]
@timcreative any progress on this? Not happy about buying PRO and first thing it's not compiling. Tried new download today and still 2.0.2. Looks like this issue has been here for 2 weeks now. 

Is the project still alive or should we refund and use another theme? So we don't spend time and money into something that is discontinued.

**Comment by dragosct10** [comment]
Hi, @fbacker! Thank you for using our product. Did you bought the product from https://themes.getbootstrap.com/ or from our site? Regards, Dragos

**Comment by fbacker** [comment]
themes.getbootstrap.com

**Comment by dragosct10** [comment]
Hi! Until the end of this day, we will make an update to the themes.getbootstrap.com and you can download from there. If you want the product now you can make an account on our site and I will give you the latest version of the product. Regards, Dragos

**Comment by fbacker** [comment]
I've filed a support request(2259) regarding this. Cheers

**Comment by groovemen** [comment]
Hello guys,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
