### ISSUE TITLE
Datepicker not working inside a modal

### ISSUE THREAD

**Issue by lightbringer2994** [creativetimofficial/ct-material-kit-pro#65]
I have the following markup:

```
<div class="col-lg-4 col-xs-8 ">
    <div class="classroom-button-width mx-auto">
        <a href="#ba" data-toggle="modal" data-target="#lesson-modal">
            <div class="classroom-button">
                <img class="icon-image" id="icon-create"
                     src="/public/images/svg/lesson.svg">
                <span><b>Create Lesson</b></span>
            </div>
        </a>
    </div>
</div>
<div class="modal fade" id="lesson-modal" tabindex="-1" role="dialog">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header ">
                <h5 class="modal-title"><b>Create Lesson</b></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="material-icons">clear</i>
                </button>
            </div>
            <div class="modal-body">
                <form name="createLesson" class="form" method="post"
                      action="#">
                    <div class="card-body">
                        <input type="text" class="form-control" id='datetimepicker1'/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
```
when i click on "datetimepicker1" input field, the datepicker popup appears just fine. But on clicking on a particular date, it keeps flickering and that date is not registered. After trying many times, it registers the click on a particular date, once in a while. How to correct this behavior?

Javascript initialization:
```
<script>
    $(function () {
        $('#datetimepicker1').datetimepicker();
    });
</script>
```

The datepicker works just fine on the same page, outside the modal.

**Comment by dragosct10** [comment]
Hi, @lightbringer2994! Thank you for using our product. Please see this [link](https://www.creative-tim.com/product/material-kit-pro?page=2#comment-6703). Some users had the same problem like you and someone gave a solution with a video. If this will not work I will help you. 

Regards,
Dragos

**Comment by Raiven66** [comment]
Hi,
Experiencing the same issue.
Copying here the reason this is happening, as found by @gbinu47, I can confirm this.

**DateTimePicker does not work properly inside a form tag**

To use this in a form, probably a way would be to copy the date to some different form element via JS.

**Comment by sahilbabu** [comment]
Hi @dragosct10 
I'm using pro version 
datepicker not working within form tag

`			    <form  class="form">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="label-control">Datetime Picker</label>
                                        <input type="text" class="form-control datetimepicker" value="10/05/2016">
                                    </div>
                                    <div class="form-group">
                                        <label class="label-control">Date Picker</label>
                                        <input type="text" class="form-control datepicker" value="10/10/2016">
                                    </div>
                                    <div class="form-group">
                                        <label class="label-control">Time Picker</label>
                                        <input type="text" class="form-control timepicker" value="14:00">
                                    </div>
                                </div>
                            </div>
                        </div>
</form>`

it is continuously blinking.

**Comment by dragosct10** [comment]
Hi, @sahilbabu! After you will put the uploaded library in your project also this error will disappear for you. Regards, Dragos

**Comment by sahilbabu** [comment]
Thank you @dragosct10 It's working now

**Comment by davidsearle** [comment]
Hi, how can I download the zip file?  It appears unavailable to me.


Thanks

**Comment by naufaldxdfam** [comment]
Can i get the zip file ?

**Comment by VincentdeWit94** [comment]
They've changed the repository name, you can find the updated link [here](https://github.com/creativetimofficial/ct-material-kit-pro/files/1894586/bootstrap-material-design.js.zip).

**Comment by VincentdeWit94** [comment]
@dragosct10 I've updated the file but it doesn't seem to fix the datetimepicker in form problem. It still flickers when hovering over icons and is still not responding to any clicks.

**Comment by groovemen** [comment]
Please let us know what version of the product are you using?

**Comment by BatsIhor** [comment]
Hey, just bought your theme couple of days ago and I have the same issue. Didn't try that file that you have attached here as I assume your latest version has fix for that, right? 
What else can I try to make it work in modal.
Thank you
