### ISSUE TITLE
noUiSlider pip and tooltip styles missing?

### ISSUE THREAD

**Issue by burroz** [creativetimofficial/ct-material-kit-pro#66]
It seems that scale/pip or tooltips are not styled, right?

I simply added a slider like this:

```
var slider = document.getElementById('slider');
noUiSlider.create(slider, {
    behaviour: 'tap',
    start: 40,
    step: 10,
    range: {
        'min':  10,
        'max': 100
    },
    connect: [ true, false ],
    tooltips: true,
    pips: {
        mode: 'range'
    }
});
```

and this is what I get so see :-(

<img width="852" alt="screenshot" src="https://user-images.githubusercontent.com/10438933/36327769-eb222548-135f-11e8-8a32-9d2fed8a0c57.png">

I would have expected something more like this: https://refreshless.com/nouislider/pips/

**Comment by dragosct10** [comment]
Hi, @burroz! Thank you for using our product. Yes, you have right. We just styled a default slider without any options, because you know if you took every option to style it was a large amount of work to do so we just limited to a simple example. Regards, Dragos

**Comment by burroz** [comment]
this is quite bad! 👎

**Comment by tkutku** [comment]
Hi, have you already made the style updates for the slider options?
