### ISSUE TITLE
"demo" undefined in material-dashboard.js

### ISSUE THREAD

**Issue by osmanovv** [creativetimofficial/ct-material-kit-pro#69]
There is `"demo" undefined` exception in `material-dashboard-pro-html-v1.2.1\assets\js\material-dashboard.js` (line 214):

<pre>
  // activate collapse right menu when the windows is resized
  $(window).resize(function() {
      md.initSidebarsCheck();

      // reset the seq for charts drawing animations
      seq = seq2 = 0;

      setTimeout(function() {
          demo.initDashboardPageCharts();
      }, 500);
  });
</pre>

While template says:
<pre>
  &lt;!--  CSS for Demo Purpose, don't include it in your project     --&gt;
  &lt;link href="../assets/css/demo.css" rel="stylesheet" /&gt;

...

  &lt;!-- Material Dashboard DEMO methods, don't include it in your project! --&gt;
  &lt;script src="../assets/js/demo.js"&gt;&lt;/script&gt;
</pre>

Actually, this is the issue for https://github.com/creativetimofficial/material-dashboard project.

**Comment by dragosct10** [comment]
Hi, @osmanovv! Sorry for the late response. Do you receive an error in your console browser? 

Regards, 
Dragos

**Comment by osmanovv** [comment]
Hi, Dragos. I just want to say, that there is a reference to `demo` object from `demo.js` in `material-dashboard.js`, so material dashboard won't work without referencing demo.js in other projects.

**Comment by dragosct10** [comment]
Hi, @osmanovv! Thank you for this observation. You have right this issue must be fixed and we will fixed in the next release. Regards, Dragos

**Comment by groovemen** [comment]
Hello @osmanovv,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
