### ISSUE TITLE
Multiple back-end manually rotating card

### ISSUE THREAD

**Issue by zitengine** [creativetimofficial/ct-material-kit-pro#70]
Hi,
I need to Create a form. It's have 4 part [ Profile, Info, Service, payment info ]
I want to make 4 back in one card with button click option.
can you tell me what to change at your code.

**Comment by dragosct10** [comment]
Hi, @zitengine! Thank you for using our product. It's kind of complicate what you want to do because you must add also javascript code there and it's a complex work because you want 4 back of the card. Can you show us an example? 

Regards, Dragos

**Comment by zitengine** [comment]
for example this is done by Nav fill, I want to do it by card rotating,
My main objective is Make multiple form Part
https://www.bootply.com/120472
