### ISSUE TITLE
Select Bootstrap Selectpicker and Color format not working !

### ISSUE THREAD

**Issue by emanuelnogueiras** [creativetimofficial/ct-material-kit-pro#71]
According to the documentation, adding the color format of the buttons works.

btn-info or some

But it does not work. How can I do ?
I want it to be red (danger)

```
<select name="lang" id="lang" class="selectpicker" data-style="btn-danger select-with-transition" title="Seleccione una de las opciones" data-size="7">
<option value="EN">Inglés</option>
<option selected value="ES">Español</option>
<option value="FR">Francés</option>
<option value="PT">Portugués</option>
<option value="DE">Alemán</option>
</select>
```

**Comment by dragosct10** [comment]
Hi, @emanuelnogueiras! Thank you for using our product. Please put on the attribute `data-style` the class `btn btn-danger` not only the class `btn-danger`. Regards, Dragos

**Comment by emanuelnogueiras** [comment]
`<select name="idioma" id="idioma" class="selectpicker" data-style="select-with-transition btn btn-danger" title="Seleccione una de las opciones" data-size="7">`

It doesn't work with "BTN BTN-DANGER" neither...
I am using the select picker "choose city" from the forms extended example page
Take a look to the "choose city" select and then you can see that it doesn't work...
This code (btn btn-colorstyle) only work with the others select, but with this one does not.

I want to use this one...

```
<div class="col-lg-5 col-md-6 col-sm-3">
  <select class="selectpicker" data-style="btn btn-danger select-with-transition" title="Choose City" data-size="7">                                                        
    <option value="2">Paris </option>
    <option value="3">Bucharest</option>
    <option value="4">Rome</option>
    <option value="5">New York</option>
  </select>
</div>
```

As you can see in the last one, I have put the btn danger tag but it is still showing the pourple color in the list

Please help !!

**Comment by dragosct10** [comment]
Hi, @emanuelnogueiras! Please, let me know on which product did you work, because this issue is opened on material kit pro repo and you said the the select picker that you use id from forms extended example page which is in the material dashboard pro product? Regards, Dragos

**Comment by emanuelnogueiras** [comment]
Yes, I have purchase  material dashboard pro product.

**Comment by deepfriedbrain** [comment]
I have the same problem. On top of it, I can't make it as a rounded button (btn-rounded). 

I have also purchased the MKP Pro product.

**Comment by dragosct10** [comment]
Hi, @deepfriedbrain! Thank you for using our product. Do you want to have the elements from the select to be with another color on hover, right? Regards, Dragos

**Comment by deepfriedbrain** [comment]
Hi, I can get the color to change, but I want to have the rounded buttons as we had in 1.x version (screenshot below). I can't seem to get it to work in 2.x.  

![image](https://user-images.githubusercontent.com/1531669/39231595-2c7cc1ca-489d-11e8-8264-626d01bf91b1.png)

**Comment by dragosct10** [comment]
Hi! In the first version, the rounded buttons were not correctly used for select because it's not ok for example when you have a form in your page to complete and you have a button rounded with select and a button with finish submit. This is annoying and for this reason the select must be like an input not like a button. I hope you understand this. Regards, Dragos

**Comment by deepfriedbrain** [comment]
Well, form is just one of the several use cases. I'm using rounded buttons on pages without a form where user can select a pricing plan and select the buy now button. It looks great on my page and I would really like to get it working the same way. Can you provide a version of the rounded select button for backward compatibility? Even if you don't add it to your package, as long as you can provide me the implementation, I can add it to my project. 

Hope you understand my point of view as well. Thanks.

**Comment by dragosct10** [comment]
Hi! Yes, I understand your point of view and we will help you. I will provide you a separately scss for the select to make them rounded. Regards, Dragos

**Comment by deepfriedbrain** [comment]
Hi @dragosct10 

This is one of the last two items (other one is an issue with carousel) holding up my project's migration to MKP v2.x / Bootstrap 4. Do you have estimate of when you can provide the scss for the rounded button select? I tried to do it myself and have come close, but it still has a few issues. 

Thanks in advance.

**Comment by groovemen** [comment]
Hello @emanuelnogueiras, thank you for using our products, you have to use only these classes on the **data-style** attribute: `btn btn-danger btn-round`! without the **select-with-transition**
Best, 
Stefan
