### ISSUE TITLE
scss not working on rails

### ISSUE THREAD

**Issue by michelson** [creativetimofficial/ct-material-kit-pro#72]
ref https://github.com/creativetimofficial/material-kit/issues/106

**Comment by Deb-Penny** [comment]
Receiving this error in RoRails 5.1.6, sass 3.5.6, BS4 beta 2.1 and 4.0.0

app/assets/stylesheets/core/mixins/_utilities.scss:53
app/assets/stylesheets/core/_mixins.scss:1
app/assets/stylesheets/material-kit.scss:15


Mixins may not be defined within control directives or other mixins.
`} @mixin create-colored-badges(){   
     @mixin badge-color($color){         
           .tag{            
             background-color: $color;
             color: $white-color;
`
on mixins-badges and -buttons.


Cannot compile

**Comment by dragosct10** [comment]
Hi, @Deb-Penny! Thank you for using our product. Please take the latest version of the product 2.0.3. Regards, Dragos
