### ISSUE TITLE
Bootstrap Select bug with keyboard inputs

### ISSUE THREAD

**Issue by brendanlayton** [creativetimofficial/ct-material-kit-pro#73]
Hi

There's a bug with the Bootstrap Select plugin when you use keyboard inputs. To illustrate the bug go to the example select menu you have here - http://demos.creative-tim.com/material-kit-pro/docs/2.0/plugins/select-bootstrap.html. If you click on the select menu with your mouse but then type "is" (in this example you're searching for "Is great"), it will highlight the "Is great" option. Then if you press the enter button on your keyboard the select menu selects it and instead of closing it then opens up again. From that point onwards it's impossible to close the select menu again without refreshing the page.  

![screen shot 2018-03-01 at 3 47 15 pm](https://user-images.githubusercontent.com/17167127/36863218-e0e7210c-1d67-11e8-88e2-c8baaf191a85.jpg)
(As the screenshot shows, if you press the "Enter" key to select a menu item the select menu remains open and it is then impossible to close it).

Many people use keyword inputs when the select menu is long, e.g. for a list of states/provinces. The issue occurs in Chrome and Firefox...I haven't tested it elsewhere. Also, the standard Bootstrap select menu works fine and so too the select menus by Silvio Moreto - http://silviomoreto.github.io/bootstrap-select/examples/

**Comment by dragosct10** [comment]
Hi, @brendanlayton! Thank you for using our product. We will check it and we will come back with an answer. Regards, Dragos

**Comment by brendanlayton** [comment]
Hi @dragosct10. Any luck with this?

If there's no simple solution then I'll need to pull this from the site I'm building. I'd like to replace them with either Bootstap's dropdowns or Silvio Moreto's dropdowns, both of which work with keyboard inputs. However, when I add their respective codes to my site it continues not to work  - there's obviously something in the Material Kit Pro custom code that is preventing the dropdowns from working as they should. Therefore, can you suggest which sass/js files I'd need to disable/remove in order to make this work?

**Comment by randallmlough** [comment]
> First option will be to give the library that is now in the product with some modification in it or if you want to wait untill we update the product with the new version of the library which support the BS4 version.

@dragosct10 I've seen a similar reply in other threads, can you release the library for the new select picker for your this?

**Comment by dragosct10** [comment]
Hi, @randallmlough! Thank you for using our product. In the last version of the product that issues are fixed. Regards, Dragos

**Comment by msarfernandez** [comment]
Hi, there is a similar issue when user navigates a dropdown with keyboard up or down. From bottom to top, does not navigate more than two items. From top to bottom does not navigate at all. Have you seen this? 
Regards.

**Comment by groovemen** [comment]
Hello @brendanlayton,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan

**Comment by itasouza** [comment]
This selectpicker does not work correctly when we try to select an option, sometime the content is not selected, a problem similar to what happens to the datetimepicker inside form
