### ISSUE TITLE
Bad view in IE and Safari

### ISSUE THREAD

**Issue by PavelValentov** [creativetimofficial/ct-material-kit-pro#74]
I use Material Kit Pro Version 2.0.2.

It is good displaying in Chrome.
Please say, what can I do for normal display my syte in  last versions of IE11 and Safari?

Screenshots here,
Chrome:
https://yadi.sk/i/N4KQ9msC3SyKvW

Safari
https://yadi.sk/i/FgGSw5r63SyKyR

IE11:
https://yadi.sk/i/UO9wJvA73SyKtr

**Comment by dragosct10** [comment]
Hi, @PavelValentov! Thank you for using our product. Since Apple discontinued safari on Windows many years ago ( 
https://discussions.apple.com/thread/6573068 ) we don't offer support for this browser. Regard on IE11 we will check and we will come with an answer. Regards, Dragos

**Comment by PavelValentov** [comment]
Thank you. We will waiting for...

**Comment by groovemen** [comment]
Hello @PavelValentov,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
