### ISSUE TITLE
Active when colapsed isn't visible

### ISSUE THREAD

**Issue by chrisjenx** [creativetimofficial/ct-material-kit-pro#76]
<img width="321" alt="screen shot 2018-03-09 at 17 11 56" src="https://user-images.githubusercontent.com/1167793/37235591-ffa23630-23bc-11e8-920b-7a46e87366bf.png">
vs
<img width="356" alt="screen shot 2018-03-09 at 17 12 17" src="https://user-images.githubusercontent.com/1167793/37235600-0b897fa8-23bd-11e8-887c-aaef918d0868.png">

**Comment by chrisjenx** [comment]
Hey still no fix for this. Any progress?

**Comment by dragosct10** [comment]
Hi, @chrisjenx! Sorry for the late response and thank you for using our product.  Do you use the latest version of the product? Regards, Dragos

**Comment by chrisjenx** [comment]
Yeah, using 2.0.3, still have the same problem :(

**Comment by dragosct10** [comment]
Hi, @chrisjenx! Please, can you give us your link to the project? Regards, Dragos

**Comment by chrisjenx** [comment]
HTTPS://bcjnetworks.com

**Comment by dragosct10** [comment]
Hi, @chrisjenx! Please see the image below to see how to solve this issue with a simple css. 

<img width="399" alt="screen shot 2018-05-16 at 09 36 52" src="https://user-images.githubusercontent.com/17456857/40100517-d7d9f358-58ec-11e8-912e-02f91fe259b4.png">

Hope this will help you! 

Regards,
Draogos

**Comment by chrisjenx** [comment]
Ah nice. Thanks!
