### ISSUE TITLE
Update index.html to prevent confusion about gulp compile-scss

### ISSUE THREAD

**Issue by kawaijoe** [creativetimofficial/ct-material-kit-pro#78]
Hello

I am suggesting that the authors update the sample index.html file on line 17.

```html
<!-- From -->
<link rel="stylesheet" href="./assets/css/material-kit.css?v=2.0.2">
<!-- To -->
<link rel="stylesheet" href="./assets/css/material-kit-pro.css?v=2.0.2">
```

Referring to the [documentation](http://demos.creative-tim.com/material-kit-pro/docs/2.0/components/colors.html), I was puzzled why the colors were not updating despite following the guide step by step. A little note in the documentation or an update to the index.html file will be nice.

Thank you!

PS. As raised in issue #60, I believe that he is experiencing the same issue.

**Comment by groovemen** [comment]
Hello @kawaijoe,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
