### ISSUE TITLE
Contact Component - Google Map

### ISSUE THREAD

**Issue by elvnthaus** [creativetimofficial/ct-material-kit-pro#8]
Is there documentation on how to customize the google map in the 'Contact Us 2' component so that it shows a location other than Bucharest?

**Comment by alexandru-paduraru** [comment]
@elvnthaus thank you for using our product. Here is how you can find anything about the plugins. 

1. You can see that the id in `sections.html` is `contactUs2Map`
2. If you go at the end of the page you fill find this function: `materialKitDemo.initContactUs2Map();`
3. Go to `assets/js/material-kit.js` and search for `initContactUs2Map()`, it will be around line 144
4. Change the coordinates 144 and 145.

Hope this helps you. Best, Alex!

**Comment by elvnthaus** [comment]
If I'm using the Angular4, how would I get `materialKitDemo.initContactUs2Map();` to execute onNgInit so that the map is ready by the time the component html loads?

**Comment by alexandru-paduraru** [comment]
@elvnthaus from what we know, Angular 4 is not so different than Angular 2, please check this example that we have for Angular2 dashboard's map: https://github.com/creativetimofficial/light-bootstrap-dashboard-angular/tree/master/app/dashboard/maps. Hope that will help you.

Best,
Alex
