### ISSUE TITLE
Gulp compile issue

### ISSUE THREAD

**Issue by cognitive-ai** [creativetimofficial/ct-material-kit-pro#80]
I keep getting the below type errors on lots of lines with the material kit pro

E:\WebSite>gulp compile-scss
[05:05:21] Using gulpfile E:\WebSite\gulpfile.js
[05:05:21] Starting 'compile-scss'...
Error in plugin 'sass'
Message:
    assets\scss\core\mixins\_buttons.scss

Error: argument `$color` of `darken($color, $amount)` must be a color

       Backtrace:
        assets/scss/core/mixins/_buttons.scss:170, in function `darken`
        assets/scss/core/mixins/_buttons.scss:170, in mixin `bmd-raised-button-variant`
        assets/scss/core/mixins/_buttons.scss:210, in mixin `bmd-raised-button-color`
        assets/scss/core/_buttons.scss:22
        on line 170 of assets/scss/core/mixins/_buttons.scss
>>   $focus-border: darken($border, 12%);
   -----------------^

**Comment by groovemen** [comment]
Hello @cognitive-ai,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan

**Comment by dev-procedural** [comment]
Hi ,

   I'm having the exact same problem bought the 2.1.1. Find the detail below. I'm only trying to change _brand.scss. Would it be please possible some help here?, thanks in advance.
`
└──╼ $ node --version
v10.19.0

└──╼ $ gulp --version
CLI version: 2.2.0
Local version: 3.9.1
`
