### ISSUE TITLE
Embedding video using Bootstrap 4 recommendations not working

### ISSUE THREAD

**Issue by jeffdeville** [creativetimofficial/ct-material-kit-pro#83]
Dropping in this (from https://getbootstrap.com/docs/4.0/utilities/embed/)
```
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zpOULjyy-n8?rel=0" allowfullscreen></iframe>
</div>
```

Does not render the video.  The space is allocated, but the video is not rendered.  (It does work in the bootstrap docs page I linked to though) 

@timshingyu

**Comment by dragosct10** [comment]
Hi, @jeffdeville! Thank you for using our product. Why do you not use the iframe code that we have in the sections headers from the product because there everything is working fine? Regards, Dragos

**Comment by jeffdeville** [comment]
Thanks @dragosct10, That works great!  May I suggest that you copy/paste the tesla demo into the docs' components section labeled Video (by the carousel demo seems to make the most sense to me).  

I'm ordinarily good at searching for examples of what I want, but this behavior differs from the underlying theme, and was not an obvious find in your docs. I figure it's likely something I won't be the last to have trouble finding the example.

Thank you for the prompt reply!
