### ISSUE TITLE
Bootstrap Select bug with data-live-search option

### ISSUE THREAD

**Issue by nicolasducere** [creativetimofficial/ct-material-kit-pro#86]
Hello,

For my website I need to be able to provide search feature in my selectpickers as I have large lists of values.

But this feature is currently broken with your kit, for the example, in your example file, I add data-live-search="true" to the multiple select attributes like this :

```
<select class="selectpicker" data-style="select-with-transition" data-live-search="true" multiple title="Choose City" data-size="7">
     <option disabled> Choose city</option>
     <option value="2">Paris </option>
     <option value="3">Bucharest</option>
     <option value="4">Rome</option>
     <option value="5">New York</option>
     <option value="6">Miami </option>
     <option value="7">Piatra Neamt</option>
     <option value="8">Paris </option>
     <option value="9">Bucharest</option>
     <option value="10">Rome</option>
     <option value="11">New York</option>
     <option value="12">Miami </option>
     <option value="13">Piatra Neamt</option>
     <option value="14">Paris </option>
     <option value="15">Bucharest</option>
     <option value="16">Rome</option>
     <option value="17">New York</option>
     <option value="18">Miami </option>
     <option value="19">Piatra Neamt</option>
</select>
```

But when I refresh the page, I have the search field but the filtered results are not updated when typing :

![image](https://user-images.githubusercontent.com/6095038/38550776-ae3ed15e-3cb7-11e8-8da1-5a90fd2b519b.png)

Thanks !

**Comment by dragosct10** [comment]
Hi, @nicolasducere! Thank you for using our product. The problem with this plugin is that we use a version of this plugin that is compatible with BS3 only because when we released our product, the BS4 version of the selectpicker was not released, meanwhile that version appeared and we have two options for you now. First will be to wait until we made an update with the final version of the plugin, or second is to give you the the library with some modifications in it.

Regards,
Dragos

**Comment by nicolasducere** [comment]
Hello !

Thank you for your answer !

Modification is ok, I mean waiting for the final version, as I need it to be fixed ASAP.

**Comment by nicolasducere** [comment]
Hello !

Any news here ?

Thanks

**Comment by dragosct10** [comment]
Hi! Sorry for the late response. To fix the problem please add in the scss the following lines of code:

```css
.bootstrap-select .hidden{
  display: none;
}
``

Regards, 
Dragos

**Comment by groovemen** [comment]
Hello @nicolasducere,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan

**Comment by indradio** [comment]
> ```css
> .bootstrap-select .hidden{
>   display: none;
> }
> ```

Thx, this work for me

**Comment by parvez-cet21** [comment]
Hi everyone, I'm using tagsinput for select, I just want to add only the select options as tags, and also want to add live-search for the options. @indradio  I have already tried with above method but doesn't work for me as I believe thats for selectpicker 'class'
```
<select data-role="tagsinput" name="independent" multiple data-live-search='true' data-live-search-style="startsWith" >
        <option>Lorem</option>
	<option>Ipsum</option>
	<option>Dummy</option>
</select>
```
