### ISSUE TITLE
Switch Toggle not working

### ISSUE THREAD

**Issue by KatherineGraham** [creativetimofficial/ct-material-kit-pro#89]
![screen shot 2018-04-11 at 4 27 01 pm](https://user-images.githubusercontent.com/38301720/38648279-39210d94-3da5-11e8-87d8-aa8c49b0d2ef.png)

Above is my code, the switches on my page all look like this, none of them are toggling.

**Comment by KatherineGraham** [comment]
Is there a specific JS file I need to include to use the toggles? 

I thought I included all of them but text boxes don't even work.

**Comment by dragosct10** [comment]
Hi, @KatherineGraham! In our part like you saw the toggles are working fine. Please give us your link project because in this way we can't help you. Regards, Dragos

**Comment by KatherineGraham** [comment]
I am just wondering if there is a file we need to include for them. I used the same HTML as indicated in the documentation, and the switches show up they just don't toggle. I don't have my project available on here.

**Comment by dragosct10** [comment]
Hi! The switches are integrated into bootstrap-material-design.js so you don't have to include any js file particularly, but maybe you have some javascript in your project that stop any event on the switches. It's a weird issue because it's the first time when someone is telling us that the switches are not working. Please try to put exact the same code like here: 

```html
<div class="togglebutton">
    <label>
        <input type="checkbox" checked="">
        <span class="toggle"></span>
        Toggle is on
    </label>
</div>
``` 
Regards,
Dragos

**Comment by KatherineGraham** [comment]
I get a compilation error from webpack when I put that exact clode in because the input has no close. When I close it then the switches don't work. I can't run the code without a close in the input.

Is closing the input causing my problem?

**Comment by dragosct10** [comment]
Hi, @KatherineGraham! I don't know exactly if this is the problem but you must try to put the input like this: 

```html
<input type="checkbox" checked="" />
```
Regards,
Dragos
