### ISSUE TITLE
Disabled button gets drop shadow and hand cursor

### ISSUE THREAD

**Issue by deepfriedbrain** [creativetimofficial/ct-material-kit-pro#91]
I'm migrating from MKP 1.x to 2.x. 

I noticed that in 2.x the disabled button gets a hand cursor and a drop shadow when it's hovered over. However, it wasn't like this in 1.x where it had a cursor with a stop sign (striked out circle) and without a drop shadow. I confirmed this issue in the [documentation](https://demos.creative-tim.com/material-kit-pro/docs/2.0/components/buttons.html) as well.

I think the 1.x implementation was the correct implementation. Is this an intentional change or a bug in 2.x?

**Comment by groovemen** [comment]
Hello @deepfriedbrain, thank you for using our template, we'll fix this issue in the next update, all you have to do until then is to set some properties for the `.btn-disabled` class:  `cursor: not-allowed;` and for the **:hover** state, `.btn-disabled:hover` set: `box-shadow: none;`

Hope these informations helps you!
Best, Stefan

**Comment by deepfriedbrain** [comment]
Thanks, I managed to fix it with your suggestion.
