### ISSUE TITLE
Rollup modules

### ISSUE THREAD

**Issue by randallmlough** [creativetimofficial/ct-material-kit-pro#93]
From what I gather in the comments of `bootstrap-material-design.js` it seems that you are using [Rollup](https://rollupjs.org/guide/en) to bundle your scripts together. Any chance you guys would be willing to allow us pro members the modular/individual script files? There's scripts I particularly don't need and there's also a couple I'd like to add. This would be a huge benefit to be able to compartmentalize all of this.

**Comment by dragosct10** [comment]
Hi, @randallmlough! Thank you for using our product. You can download the project from [bootstrap material design](https://fezvrasta.github.io/bootstrap-material-design/) and there you will find all the js partials from the rollup and you can take them and rollup the js with any partials you want. Regards, Dragos
