### ISSUE TITLE
About minified material-kit.js

### ISSUE THREAD

**Issue by deepfriedbrain** [creativetimofficial/ct-material-kit-pro#94]
I noticed that in the 2.0.3 package, the js folder has material-kit and material-kit.min.js. But material-kit.js is actually the minified version, and material-kit.min.js is the non-minified one. Are the file names incorrect or am I missing something?

**Comment by groovemen** [comment]
Hello @deepfriedbrain, thank you for using our template, you are right, we have also noticed this issue, and we will resolve it as quickly as possible in the next update. I will ask you to rename the files properly, and I hope you will not get tangled about it. 
Best, Stefan

**Comment by groovemen** [comment]
Hello @deepfriedbrain,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
