### ISSUE TITLE
Issue with Product Page - Can't get any of the JS to work on Shopify Store

### ISSUE THREAD

**Issue by binkster24** [creativetimofficial/ct-material-kit-pro#95]
My store isn't allowing for javascript to work. I keep getting this:

<img width="2086" alt="screen shot 2018-04-26 at 11 58 39 am" src="https://user-images.githubusercontent.com/30815021/39317446-9731ab5a-4949-11e8-8918-c6e78931e642.png">

Errors coming up in console

<img width="549" alt="screen shot 2018-04-26 at 12 00 57 pm" src="https://user-images.githubusercontent.com/30815021/39317450-9ae6cb54-4949-11e8-9d75-8aee5e3565e7.png">

I have tried many different online solutions, but none have worked on the shopify platform. Please help!

This is the code for both my theme.liquid 

`<!doctype html>

 <html class="no-js supports-no-cookies" lang="{{ shop.locale }}"> 
<head>

    

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="{{ settings.color_primary }}">
  <link rel="canonical" href="{{ canonical_url }}">

  {% if settings.favicon != blank %}
    <link rel="shortcut icon" href="{{ settings.favicon | img_url: '32x32' }}" type="image/png">
  {% endif %}

  {% capture seo_title %}
    {{ page_title }}
    {% if current_tags %}
      {%- assign meta_tags = current_tags | join: ', ' %} &ndash; {{ 'general.meta.tags' | t: tags: meta_tags -}}
    {% endif %}
    {% if current_page != 1 %}
      &ndash; {{ 'general.meta.page' | t: page: current_page }}
    {% endif %}
    {% unless page_title contains shop.name %}
      &ndash; {{ shop.name }}
    {% endunless %}
  {% endcapture %}
  <title>{{ seo_title }}</title>

  {% if page_description %}
    <meta name="description" content="{{ page_description | escape }}">
  {% endif %}

  {% include 'social-meta-tags' %}

  <script>
    document.documentElement.className = document.documentElement.className.replace('no-js', 'js');

    window.theme = {
      strings: {
        addToCart: {{ 'products.product.add_to_cart' | t | json }},
        soldOut: {{ 'products.product.sold_out' | t | json }},
        unavailable: {{ 'products.product.unavailable' | t | json }}
      },
      moneyFormat: {{ shop.money_format | json }}
    };
  </script>

  {% if template.directory == 'customers' %}
    <script src="{{ 'shopify_common.js' | shopify_asset_url }}" defer="defer"></script>
    
  {% endif %}

  <script src="{{ 'vendor.js' | asset_url }}" defer="defer"></script>
  

  
  
  {{ content_for_header }}
  
  
  
  
  
  {{ 'material-kit.css' | asset_url | stylesheet_tag }} 
   
   
 
</head>

<body id="{{ page_title | handle }}" class="template-{{ template.name | handle }}">
  
   
  

  
    {{ content_for_layout }}
 

  {% section 'footer' %}
 
 
   
  {{ 'jquery.min.js' | asset_url | script_tag }}
  {{ 'popper.min.js' | asset_url | script_tag }}
  {{ 'bootstrapmaterialdesign.min.js' | asset_url | script_tag }}
    {{ 'moment.min.js' | asset_url | script_tag }}
    
{{ 'bootsrapdatetimepicker.min.js.liquid' | asset_url | script_tag }}
    
{{ 'nouislider.min.js' | asset_url | script_tag }}
    
{{ 'bootstrapselectpicker.js' | asset_url | script_tag }}
    
{{ 'bootstraptagsinput.js' | asset_url | script_tag }}
    
{{ 'jasnybootstrap.js' | asset_url | script_tag }}
    
{{ 'jquery.flexisel.js' | asset_url | script_tag }}
    
{{ 'modernizr.min.js' | asset_url | script_tag }}
{{ 'veritcalnav.js' | asset_url | script_tag }}
    
{{ 'materialkit.js' | asset_url | script_tag }}  
{{ 'materialkitdemo.js' | asset_url | script_tag }} 
{{ 'gulpfile.js' | asset_url | script_tag }}      
    

  
  
</body>
</html>
`

Code for the product.liquid

`<body class="product-page ">
    {% section 'nav' %} 
  <div class="rte">
    <div class="page-header header-filter" data-parallax="true" filter-color="rose" style="background-image: url(&apos;../assets/img/kit/pro/bg6.jpg&apos;);">
        <div class="container">
            <div class="row title-row">
                <div class="col-md-4 ml-auto">
                    <button class="btn btn-white float-right"><i class="material-icons">shopping_cart</i> 0 Items</button>
                </div>
            </div>
        </div>
    </div>
    <div class="section section-gray">
        <div class="container">
            <div class="main main-raised main-product">
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <div class="tab-content">
                            <div class="tab-pane" id="product-page1">
                                <img src="../assets/img/kit/pro/examples/product1.jpg">
                            </div>
                            <div class="tab-pane active" id="product-page2">
                                <img src="../assets/img/kit/pro/examples/product2.jpg">
                            </div>
                            <div class="tab-pane" id="product-page3">
                                <img src="../assets/img/kit/pro/examples/product3.jpg">
                            </div>
                            <div class="tab-pane" id="product-page4">
                                <img src="../assets/img/kit/pro/examples/product4.jpg">
                            </div>
                        </div>
                        <ul class="nav flexi-nav" data-tabs="tabs" id="flexiselDemo1">
                            <li class="nav-item">
                                <a href="#product-page1" class="nav-link" data-toggle="tab">
                                    <img src="../assets/img/kit/pro/examples/product1.jpg">
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#product-page2" class="nav-link" data-toggle="tab">
                                    <img src="../assets/img/kit/pro/examples/product2.jpg">
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#product-page3" class="nav-link" data-toggle="tab">
                                    <img src="../assets/img/kit/pro/examples/product3.jpg">
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#product-page4" class="nav-link" data-toggle="tab">
                                    <img src="../assets/img/kit/pro/examples/product4.jpg">
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <h2 class="title"> Becky Silk Blazer </h2>
                        <h3 class="main-price">$335</h3>
                        <div id="accordion" role="tablist">
                            <div class="card card-collapse">
                                <div class="card-header" role="tab" id="headingOne">
                                    <h5 class="mb-0">
                                        <a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                            Description
                                            <i class="material-icons">keyboard_arrow_down</i>
                                        </a>
                                    </h5>
                                </div>
                                <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                                    <div class="card-body">
                                        <p>Eres&apos; daring &apos;Grigri Fortune&apos; swimsuit has the fit and coverage of a bikini in a one-piece silhouette. This fuchsia style is crafted from the label&apos;s sculpting peau douce fabric and has flattering cutouts through the torso and back. Wear yours with mirrored sunglasses on vacation.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="card card-collapse">
                                <div class="card-header" role="tab" id="headingTwo">
                                    <h5 class="mb-0">
                                        <a class="collapsed" data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                            Designer Information
                                            <i class="material-icons">keyboard_arrow_down</i>
                                        </a>
                                    </h5>
                                </div>
                                <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                                    <div class="card-body">
                                        An infusion of West Coast cool and New York attitude, Rebecca Minkoff is synonymous with It girl style. Minkoff burst on the fashion scene with her best-selling &apos;Morning After Bag&apos; and later expanded her offering with the Rebecca Minkoff Collection - a range of luxe city staples with a &quot;downtown romantic&quot; theme.
                                    </div>
                                </div>
                            </div>
                            <div class="card card-collapse">
                                <div class="card-header" role="tab" id="headingThree">
                                    <h5 class="mb-0">
                                        <a class="collapsed" data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                            Details and Care
                                            <i class="material-icons">keyboard_arrow_down</i>
                                        </a>
                                    </h5>
                                </div>
                                <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
                                    <div class="card-body">
                                        <ul>
                                            <li>Storm and midnight-blue stretch cotton-blend</li>
                                            <li>Notch lapels, functioning buttoned cuffs, two front flap pockets, single vent, internal pocket</li>
                                            <li>Two button fastening</li>
                                            <li>84% cotton, 14% nylon, 2% elastane</li>
                                            <li>Dry clean</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row pick-size">
                            <div class="col-md-6 col-sm-6">
                                <label>Select color</label>
                                <select class="selectpicker" data-style="select-with-transition" data-size="7">
                                    <option value="1">Rose </option>
                                    <option value="2">Gray</option>
                                    <option value="3">White</option>
                                </select>
                            </div>
                            <div class="col-md-6 col-sm-6">
                                <label>Select size</label>
                                <select class="selectpicker" data-style="select-with-transition" data-size="7">
                                    <option value="1">Small </option>
                                    <option value="2">Medium</option>
                                    <option value="3">Large</option>
                                </select>
                            </div>
                        </div>
                        <div class="row pull-right">
                            <button class="btn btn-rose btn-round">Add to Cart &#xA0;<i class="material-icons">shopping_cart</i></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="features text-center">
                <div class="row">
                    <div class="col-md-4">
                        <div class="info">
                            <div class="icon icon-info">
                                <i class="material-icons">local_shipping</i>
                            </div>
                            <h4 class="info-title">2 Days Delivery </h4>
                            <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="info">
                            <div class="icon icon-success">
                                <i class="material-icons">verified_user</i>
                            </div>
                            <h4 class="info-title">Refundable Policy</h4>
                            <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="info">
                            <div class="icon icon-rose">
                                <i class="material-icons">favorite</i>
                            </div>
                            <h4 class="info-title">Popular Item</h4>
                            <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="related-products">
                <h3 class="title text-center">You may also be interested in:</h3>
                <div class="row">
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-product">
                            <div class="card-header card-header-image">
                                <a href="#pablo">
                                    <img class="img" src="../assets/img/kit/pro/examples/card-product1.jpg">
                                </a>
                            </div>
                            <div class="card-body">
                                <h6 class="card-category text-rose">Trending</h6>
                                <h4 class="card-title">
                                    <a href="#pablo">Dolce &amp; Gabbana</a>
                                </h4>
                                <div class="card-description">
                                    Dolce &amp; Gabbana's 'Greta' tote has been crafted in Italy from hard-wearing red textured-leather.
                                </div>
                            </div>
                            <div class="card-footer justify-content-between">
                                <div class="price">
                                    <h4>$1,459</h4>
                                </div>
                                <div class="stats">
                                    <button type="button" rel="tooltip" title="Saved to Wishlist" class="btn btn-just-icon btn-link btn-rose">
                                        <i class="material-icons">favorite</i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-product">
                            <div class="card-header card-header-image">
                                <a href="#pablo">
                                    <img class="img" src="../assets/img/kit/pro/examples/card-product3.jpg">
                                </a>
                            </div>
                            <div class="card-body">
                                <h6 class="card-category text-muted">Popular</h6>
                                <h4 class="card-title">
                                    <a href="#pablo">Balmain</a>
                                </h4>
                                <div class="card-description">
                                    Balmain's mid-rise skinny jeans are cut with stretch to ensure they retain their second-skin fit but move comfortably.
                                </div>
                            </div>
                            <div class="card-footer justify-content-between">
                                <div class="price">
                                    <h4>$459</h4>
                                </div>
                                <div class="stats">
                                    <button type="button" rel="tooltip" title="Save to Wishlist" class="btn btn-just-icon btn-link">
                                        <i class="material-icons">favorite</i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-product">
                            <div class="card-header card-header-image">
                                <a href="#pablo">
                                    <img class="img" src="../assets/img/kit/pro/examples/card-product4.jpg">
                                </a>
                            </div>
                            <div class="card-body">
                                <h6 class="card-category text-muted">Popular</h6>
                                <h4 class="card-title">
                                    <a href="#pablo">Balenciaga</a>
                                </h4>
                                <div class="card-description">
                                    Balenciaga's black textured-leather wallet is finished with the label's iconic 'Giant' studs. This is where you can...
                                </div>
                            </div>
                            <div class="card-footer justify-content-between">
                                <div class="price">
                                    <h4>$590</h4>
                                </div>
                                <div class="stats">
                                    <button type="button" rel="tooltip" title="" class="btn btn-just-icon btn-link btn-rose" data-original-title="Saved to Wishlist">
                                        <i class="material-icons">favorite</i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <div class="card card-product">
                            <div class="card-header card-header-image">
                                <a href="#pablo">
                                    <img class="img" src="../assets/img/kit/pro/examples/card-product2.jpg">
                                </a>
                            </div>
                            <div class="card-body">
                                <h6 class="card-category text-rose">Trending</h6>
                                <h4 class="card-title">
                                    <a href="#pablo">Dolce &amp; Gabbana</a>
                                </h4>
                                <div class="card-description">
                                    Dolce &amp; Gabbana's 'Greta' tote has been crafted in Italy from hard-wearing red textured-leather.
                                </div>
                            </div>
                            <div class="card-footer justify-content-between">
                                <div class="price">
                                    <h4>$1,459</h4>
                                </div>
                                <div class="stats">
                                    <button type="button" rel="tooltip" title="" class="btn btn-just-icon btn-link btn-default" data-original-title="Save to Wishlist">
                                        <i class="material-icons">favorite</i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
     
  {{ 'jquery.min.js' | asset_url | script_tag }}
  {{ 'popper.min.js' | asset_url | script_tag }}
  {{ 'bootstrapmaterialdesign.min.js' | asset_url | script_tag }}
    {{ 'moment.min.js' | asset_url | script_tag }}
    
{{ 'bootsrapdatetimepicker.min.js.liquid' | asset_url | script_tag }}
    
{{ 'nouislider.min.js' | asset_url | script_tag }}
    
{{ 'bootstrapselectpicker.js' | asset_url | script_tag }}
    
{{ 'bootstraptagsinput.js' | asset_url | script_tag }}
    
{{ 'jasnybootstrap.js' | asset_url | script_tag }}
    
{{ 'jquery.flexisel.js' | asset_url | script_tag }}
    
{{ 'modernizr.min.js' | asset_url | script_tag }}
{{ 'veritcalnav.js' | asset_url | script_tag }}
    
{{ 'materialkit.js' | asset_url | script_tag }}  
{{ 'materialkitdemo.js' | asset_url | script_tag }} 
{{ 'gulpfile.js' | asset_url | script_tag }}      
    
</body>
`

**Comment by dragosct10** [comment]
Hi, @binkster24! Thank you for using our product. It seems that you don't import the scripts good because I think the liquid syntax doesn't know that you import js file, he knows that you import HTML files. Try to see how to import correctly in the liquid syntax javascript files. Regards, Dragos
