### ISSUE TITLE
Navbar and Carousel broken on IE 11

### ISSUE THREAD

**Issue by deepfriedbrain** [creativetimofficial/ct-material-kit-pro#96]
I noticed that Navbar and Carousel are not displaying properly on IE 11. Please see the screenshots below. These screenshots are from the All Components page of the toolkit. It works fine in Edge and of course the other modern browsers.

![image](https://user-images.githubusercontent.com/1531669/39472265-d8b7782c-4d7a-11e8-9815-6c6518484e7a.png)

![image](https://user-images.githubusercontent.com/1531669/39472286-ee5c6930-4d7a-11e8-890a-ca3123d41b78.png)

**Comment by dragosct10** [comment]
Hi, @deepfriedbrain! Thank you for using our product. The problem there is that bootstrap have on the `.container` div the property `flex: 1` and this is the problem. Please try to put  `flex: unset;`. Regards, Dragos

**Comment by deepfriedbrain** [comment]
Hi, it fixes the problem on navbar but not on the carousel as I don't have a container inside the carousel. I used the following to fix the problem: 

    .navbar, .carousel {
        display: block; // Original: flex
    }

It works but does it have any potential side effects?

**Comment by dragosct10** [comment]
Hi, @deepfriedbrain! I'm glad that it works for you. It's ok that you put `display: block;`, it will not have side effect theoretically. 

Regards, 
Dragos

**Comment by deepfriedbrain** [comment]
Thanks. Hope you will fix it in the next version so that it works correctly on IE 11 by default.

**Comment by groovemen** [comment]
Hello @deepfriedbrain,

Thank you for your interest in working with our products, this issue is solved in the latest version (v2.1.0).

All the best,
Stefan
