### ISSUE TITLE
Disable transition animation

### ISSUE THREAD

**Issue by chamnap** [creativetimofficial/ct-material-kit-pro#98]
Is there an easy way to disable transition animation for any components? I have tried with few ways, 
but all of them end up with the same result. Once it opens, it cannot be closed.

1. `$enable-transitions: false`
2. Adding `#collapseExample {transition: none;}`
3. Adding ` .collapsing { transition: none !important; }`

These below links works for bootstrap material design (but doesn't work on material kit pro), which is used by material kit pro.
https://codepen.io/chamnap/pen/NMjjgZ, https://codepen.io/chamnap/pen/OZmmoe

**Comment by dragosct10** [comment]
Hi, @chamnap! Thank you for using our product. The animation must be stopped on the div with class .dropdown-menu. Regards, Dragos

**Comment by chamnap** [comment]
I'm not sure I follow.

**Comment by groovemen** [comment]
Hello @chamnap, my colleague said that you have to stop the transition for the `.dropdown-menu` class. Please check the image below:
 
<img width="247" alt="screen shot 2018-07-04 at 16 11 39" src="https://user-images.githubusercontent.com/21063398/42279096-5a2f70e2-7fa5-11e8-98f1-4da6726b4f57.png">
Hope this information helps you.

All the best, 
Stefan
