### ISSUE TITLE
Changing primary color doesn't change the card's primary color

### ISSUE THREAD

**Issue by Alanvome** [creativetimofficial/ct-material-kit-pro#99]
Hi, 

I have followed the process to change the branding color, and I have used a HEW of my own to choose a new color. 
I have successfully recompiled, and the primary buttons are in the good color. But not the primary card one. I have only changed the primary color.

Do I have to do something special ?

**Comment by groovemen** [comment]
Hello @Alanvome,

Thank you for your interest in working with our products, you have to change the **bg-primary** class for example, if you have `.card .bg-info` and you change to `bg-primary`, the background of the card will turn to purple.

All the best,
Stefan
